// Code generated by ogen, DO NOT EDIT.
package api

type AddDocumentationToKnowledgeBaseRes interface {
	addDocumentationToKnowledgeBaseRes()
}

type AddFromFileRes interface {
	addFromFileRes()
}

type AddLanguageRes interface {
	addLanguageRes()
}

type AddMemberRes interface {
	addMemberRes()
}

type AddProjectRes interface {
	addProjectRes()
}

type AddPvcVoiceSamplesRes interface {
	addPvcVoiceSamplesRes()
}

type AddSharingVoiceRes interface {
	addSharingVoiceRes()
}

type AddVoiceRes interface {
	addVoiceRes()
}

type AgentTestingBulkMoveRouteRes interface {
	agentTestingBulkMoveRouteRes()
}

type AssignConversationTagsRouteRes interface {
	assignConversationTagsRouteRes()
}

type AudioIsolationRes interface {
	audioIsolationRes()
}

type AudioIsolationStreamRes interface {
	audioIsolationStreamRes()
}

type AudioNativeProjectUpdateContentEndpointRes interface {
	audioNativeProjectUpdateContentEndpointRes()
}

type AudioNativeUpdateContentFromURLRes interface {
	audioNativeUpdateContentFromURLRes()
}

type CancelBatchCallRes interface {
	cancelBatchCallRes()
}

type CancelFileUploadRouteRes interface {
	cancelFileUploadRouteRes()
}

type ConvertChapterEndpointRes interface {
	convertChapterEndpointRes()
}

type ConvertProjectEndpointRes interface {
	convertProjectEndpointRes()
}

type CreateAgentDeploymentRouteRes interface {
	createAgentDeploymentRouteRes()
}

type CreateAgentTestFolderRouteRes interface {
	createAgentTestFolderRouteRes()
}

type CreateAudioNativeProjectRes interface {
	createAudioNativeProjectRes()
}

type CreateBatchCallRes interface {
	createBatchCallRes()
}

type CreateClipRes interface {
	createClipRes()
}

type CreateConversationTagRouteRes interface {
	createConversationTagRouteRes()
}

type CreateDubbingRes interface {
	createDubbingRes()
}

type CreateFileDocumentRouteRes interface {
	createFileDocumentRouteRes()
}

type CreateFolderRouteRes interface {
	createFolderRouteRes()
}

type CreatePvcVoiceRes interface {
	createPvcVoiceRes()
}

type CreateSecretRouteRes interface {
	createSecretRouteRes()
}

type CreateServiceAccountAPIKeyRes interface {
	createServiceAccountAPIKeyRes()
}

type CreateSpeakerRes interface {
	createSpeakerRes()
}

type CreateTextDocumentRouteRes interface {
	createTextDocumentRouteRes()
}

type CreateURLDocumentRouteRes interface {
	createURLDocumentRouteRes()
}

type CreateVoiceRes interface {
	createVoiceRes()
}

type CreateWorkspaceWebhookRouteRes interface {
	createWorkspaceWebhookRouteRes()
}

type DeleteAgentDraftRouteRes interface {
	deleteAgentDraftRouteRes()
}

type DeleteAgentRouteRes interface {
	deleteAgentRouteRes()
}

type DeleteAgentTestFolderRouteRes interface {
	deleteAgentTestFolderRouteRes()
}

type DeleteAudioIsolationHistoryItemRes interface {
	deleteAudioIsolationHistoryItemRes()
}

type DeleteAuthConnectionRes interface {
	deleteAuthConnectionRes()
}

type DeleteBatchCallRes interface {
	deleteBatchCallRes()
}

type DeleteChapterEndpointRes interface {
	deleteChapterEndpointRes()
}

type DeleteChatResponseTestRouteRes interface {
	deleteChatResponseTestRouteRes()
}

type DeleteConversationRouteRes interface {
	deleteConversationRouteRes()
}

type DeleteConversationTagRouteRes interface {
	deleteConversationTagRouteRes()
}

type DeleteDubbingRes interface {
	deleteDubbingRes()
}

type DeleteInviteRes interface {
	deleteInviteRes()
}

type DeleteKnowledgeBaseDocumentRes interface {
	deleteKnowledgeBaseDocumentRes()
}

type DeleteMcpServerRouteRes interface {
	deleteMcpServerRouteRes()
}

type DeletePhoneNumberRouteRes interface {
	deletePhoneNumberRouteRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeletePvcVoiceSampleRes interface {
	deletePvcVoiceSampleRes()
}

type DeleteRagIndexRes interface {
	deleteRagIndexRes()
}

type DeleteSampleRes interface {
	deleteSampleRes()
}

type DeleteSecretRouteRes interface {
	deleteSecretRouteRes()
}

type DeleteSegmentRes interface {
	deleteSegmentRes()
}

type DeleteServiceAccountAPIKeyRes interface {
	deleteServiceAccountAPIKeyRes()
}

type DeleteSpeechEngineRes interface {
	deleteSpeechEngineRes()
}

type DeleteSpeechHistoryItemRes interface {
	deleteSpeechHistoryItemRes()
}

type DeleteToolRouteRes interface {
	deleteToolRouteRes()
}

type DeleteTranscriptByIDRes interface {
	deleteTranscriptByIDRes()
}

type DeleteVoiceRes interface {
	deleteVoiceRes()
}

type DeleteWhatsappAccountRes interface {
	deleteWhatsappAccountRes()
}

type DeleteWorkspaceWebhookRouteRes interface {
	deleteWorkspaceWebhookRouteRes()
}

type DisableRes interface {
	disableRes()
}

type DownloadSpeechHistoryItemsRes interface {
	downloadSpeechHistoryItemsRes()
}

type DubRes interface {
	dubRes()
}

type DuplicateAgentRouteRes interface {
	duplicateAgentRouteRes()
}

type EditProjectContentRes interface {
	editProjectContentRes()
}

type EditProjectRes interface {
	editProjectRes()
}

type EditPvcVoiceRes interface {
	editPvcVoiceRes()
}

type EditPvcVoiceSampleRes interface {
	editPvcVoiceSampleRes()
}

type EditServiceAccountAPIKeyRes interface {
	editServiceAccountAPIKeyRes()
}

type EditVoiceRes interface {
	editVoiceRes()
}

type EditVoiceSettingsRes interface {
	editVoiceSettingsRes()
}

type EditWorkspaceWebhookRouteRes interface {
	editWorkspaceWebhookRouteRes()
}

type ForcedAlignmentRes interface {
	forcedAlignmentRes()
}

type GetAgentKnowledgeBaseSizeRes interface {
	getAgentKnowledgeBaseSizeRes()
}

type GetAgentKnowledgeBaseSummariesRouteRes interface {
	getAgentKnowledgeBaseSummariesRouteRes()
}

type GetAgentLinkRouteRes interface {
	getAgentLinkRouteRes()
}

type GetAgentLlmExpectedCostCalculationRes interface {
	getAgentLlmExpectedCostCalculationRes()
}

type GetAgentResponseTestRouteRes interface {
	getAgentResponseTestRouteRes()
}

type GetAgentResponseTestsSummariesRouteRes interface {
	getAgentResponseTestsSummariesRouteRes()
}

type GetAgentSummariesRouteRes interface {
	getAgentSummariesRouteRes()
}

type GetAgentTestFolderRouteRes interface {
	getAgentTestFolderRouteRes()
}

type GetAgentTopicsRouteRes interface {
	getAgentTopicsRouteRes()
}

type GetAgentsRouteRes interface {
	getAgentsRouteRes()
}

type GetAudioFromSampleRes interface {
	getAudioFromSampleRes()
}

type GetAudioFullFromSpeechHistoryItemRes interface {
	getAudioFullFromSpeechHistoryItemRes()
}

type GetAudioIsolationHistoryRes interface {
	getAudioIsolationHistoryRes()
}

type GetAudioNativeProjectSettingsEndpointRes interface {
	getAudioNativeProjectSettingsEndpointRes()
}

type GetBatchCallRes interface {
	getBatchCallRes()
}

type GetBranchRouteRes interface {
	getBranchRouteRes()
}

type GetBranchesRouteRes interface {
	getBranchesRouteRes()
}

type GetChapterSnapshotEndpointRes interface {
	getChapterSnapshotEndpointRes()
}

type GetChapterSnapshotsRes interface {
	getChapterSnapshotsRes()
}

type GetChaptersRes interface {
	getChaptersRes()
}

type GetConversationAudioRouteRes interface {
	getConversationAudioRouteRes()
}

type GetConversationHistoriesRouteRes interface {
	getConversationHistoriesRouteRes()
}

type GetConversationHistoryRouteRes interface {
	getConversationHistoryRouteRes()
}

type GetConversationSignedLinkRes interface {
	getConversationSignedLinkRes()
}

type GetConversationSipMessagesRes interface {
	getConversationSipMessagesRes()
}

type GetConversationTagRouteRes interface {
	getConversationTagRouteRes()
}

type GetConversationUsersRouteRes interface {
	getConversationUsersRouteRes()
}

type GetDashboardSettingsRouteRes interface {
	getDashboardSettingsRouteRes()
}

type GetDocumentationChunkFromKnowledgeBaseRes interface {
	getDocumentationChunkFromKnowledgeBaseRes()
}

type GetDocumentationChunksFromKnowledgeBaseRes interface {
	getDocumentationChunksFromKnowledgeBaseRes()
}

type GetDocumentationFromKnowledgeBaseRes interface {
	getDocumentationFromKnowledgeBaseRes()
}

type GetDubbedFileRes interface {
	getDubbedFileRes()
}

type GetDubbedMetadataRes interface {
	getDubbedMetadataRes()
}

type GetDubbedTranscriptFileRes interface {
	getDubbedTranscriptFileRes()
}

type GetDubbingResourceRes interface {
	getDubbingResourceRes()
}

type GetDubbingTranscriptsRes interface {
	getDubbingTranscriptsRes()
}

type GetGroupsEndpointRes interface {
	getGroupsEndpointRes()
}

type GetKnowledgeBaseContentRes interface {
	getKnowledgeBaseContentRes()
}

type GetKnowledgeBaseDependentAgentsRes interface {
	getKnowledgeBaseDependentAgentsRes()
}

type GetKnowledgeBaseListRouteRes interface {
	getKnowledgeBaseListRouteRes()
}

type GetKnowledgeBaseSourceFileURLRes interface {
	getKnowledgeBaseSourceFileURLRes()
}

type GetLibraryVoicesRes interface {
	getLibraryVoicesRes()
}

type GetLiveCountRes interface {
	getLiveCountRes()
}

type GetLivekitTokenRes interface {
	getLivekitTokenRes()
}

type GetMcpToolConfigOverrideRouteRes interface {
	getMcpToolConfigOverrideRouteRes()
}

type GetModelsRes interface {
	getModelsRes()
}

type GetOrCreateRagIndexesRes interface {
	getOrCreateRagIndexesRes()
}

type GetPhoneNumberRouteRes interface {
	getPhoneNumberRouteRes()
}

type GetProjectMutedTracksEndpointRes interface {
	getProjectMutedTracksEndpointRes()
}

type GetProjectSnapshotEndpointRes interface {
	getProjectSnapshotEndpointRes()
}

type GetProjectSnapshotsRes interface {
	getProjectSnapshotsRes()
}

type GetProjectsRes interface {
	getProjectsRes()
}

type GetPronunciationDictionariesMetadataRes interface {
	getPronunciationDictionariesMetadataRes()
}

type GetPronunciationDictionaryVersionPlsRes interface {
	getPronunciationDictionaryVersionPlsRes()
}

type GetPublicLlmExpectedCostCalculationRes interface {
	getPublicLlmExpectedCostCalculationRes()
}

type GetPvcSampleAudioRes interface {
	getPvcSampleAudioRes()
}

type GetPvcSampleSpeakersRes interface {
	getPvcSampleSpeakersRes()
}

type GetPvcSampleVisualWaveformRes interface {
	getPvcSampleVisualWaveformRes()
}

type GetPvcVoiceCaptchaRes interface {
	getPvcVoiceCaptchaRes()
}

type GetRagIndexOverviewRes interface {
	getRagIndexOverviewRes()
}

type GetRagIndexesRes interface {
	getRagIndexesRes()
}

type GetResourceMetadataRes interface {
	getResourceMetadataRes()
}

type GetSecretRouteRes interface {
	getSecretRouteRes()
}

type GetSecretsRouteRes interface {
	getSecretsRouteRes()
}

type GetServiceAccountAPIKeysRouteRes interface {
	getServiceAccountAPIKeysRouteRes()
}

type GetSettingsRouteRes interface {
	getSettingsRouteRes()
}

type GetSignedURLDeprecatedRes interface {
	getSignedURLDeprecatedRes()
}

type GetSimilarLibraryVoicesRes interface {
	getSimilarLibraryVoicesRes()
}

type GetSimilarVoicesForSpeakerRes interface {
	getSimilarVoicesForSpeakerRes()
}

type GetSingleUseTokenRes interface {
	getSingleUseTokenRes()
}

type GetSpeakerAudioRes interface {
	getSpeakerAudioRes()
}

type GetSpeechHistoryItemByIDRes interface {
	getSpeechHistoryItemByIDRes()
}

type GetSpeechHistoryRes interface {
	getSpeechHistoryRes()
}

type GetTestInvocationRouteRes interface {
	getTestInvocationRouteRes()
}

type GetToolDependentAgentsRouteRes interface {
	getToolDependentAgentsRouteRes()
}

type GetToolExecutionsRouteRes interface {
	getToolExecutionsRouteRes()
}

type GetTranscriptByIDRes interface {
	getTranscriptByIDRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type GetUserVoicesV2Res interface {
	getUserVoicesV2Res()
}

type GetVersionMetadataRouteRes interface {
	getVersionMetadataRouteRes()
}

type GetVoiceByIDRes interface {
	getVoiceByIDRes()
}

type GetVoiceSettingsRes interface {
	getVoiceSettingsRes()
}

type GetVoicesRes interface {
	getVoicesRes()
}

type GetWhatsappAccountRes interface {
	getWhatsappAccountRes()
}

type GetWorkspaceBatchCallsRes interface {
	getWorkspaceBatchCallsRes()
}

type GetWorkspaceServiceAccountsRes interface {
	getWorkspaceServiceAccountsRes()
}

type GetWorkspaceWebhooksRouteRes interface {
	getWorkspaceWebhooksRouteRes()
}

type HandleExotelOutboundCallRes interface {
	handleExotelOutboundCallRes()
}

type HandleSipTrunkOutboundCallRes interface {
	handleSipTrunkOutboundCallRes()
}

type HandleTwilioOutboundCallRes interface {
	handleTwilioOutboundCallRes()
}

type InviteUserRes interface {
	inviteUserRes()
}

type InviteUsersBulkRes interface {
	inviteUsersBulkRes()
}

type ListAuthConnectionsRes interface {
	listAuthConnectionsRes()
}

type ListAvailableLlmsRes interface {
	listAvailableLlmsRes()
}

type ListChatResponseTestsRouteRes interface {
	listChatResponseTestsRouteRes()
}

type ListConversationTagsRouteRes interface {
	listConversationTagsRouteRes()
}

type ListDubsRes interface {
	listDubsRes()
}

type ListMcpServerToolsRouteRes interface {
	listMcpServerToolsRouteRes()
}

type ListPhoneNumbersRouteRes interface {
	listPhoneNumbersRouteRes()
}

type ListSipMessagesRes interface {
	listSipMessagesRes()
}

type ListSpeechEnginesRes interface {
	listSpeechEnginesRes()
}

type ListTestInvocationsRouteRes interface {
	listTestInvocationsRouteRes()
}

type ListWhatsappAccountsRes interface {
	listWhatsappAccountsRes()
}

type MergeBranchIntoTargetRes interface {
	mergeBranchIntoTargetRes()
}

type MigrateSegmentsRes interface {
	migrateSegmentsRes()
}

type PatchPronunciationDictionaryRes interface {
	patchPronunciationDictionaryRes()
}

type PostAgentAvatarRouteRes interface {
	postAgentAvatarRouteRes()
}

type PostConversationFeedbackRouteRes interface {
	postConversationFeedbackRouteRes()
}

type PostKnowledgeBaseBulkMoveRouteRes interface {
	postKnowledgeBaseBulkMoveRouteRes()
}

type PostKnowledgeBaseMoveRouteRes interface {
	postKnowledgeBaseMoveRouteRes()
}

type PublicCreateOrderRes interface {
	publicCreateOrderRes()
}

type PublicGetAvailableLanguagesRes interface {
	publicGetAvailableLanguagesRes()
}

type PublicGetMediaInfoRes interface {
	publicGetMediaInfoRes()
}

type PublicGetOrderDeliverablesRes interface {
	publicGetOrderDeliverablesRes()
}

type PublicGetOrderRes interface {
	publicGetOrderRes()
}

type PublicListOrdersRes interface {
	publicListOrdersRes()
}

type PublicRegisterMediaRes interface {
	publicRegisterMediaRes()
}

type PublicRemoveOrderItemRes interface {
	publicRemoveOrderItemRes()
}

type PublicSubmitOrderRes interface {
	publicSubmitOrderRes()
}

type PublicUpdateOrderRes interface {
	publicUpdateOrderRes()
}

type PublicUpsertOrderItemRes interface {
	publicUpsertOrderItemRes()
}

type RagIndexStatusRes interface {
	ragIndexStatusRes()
}

type RefreshURLDocumentRouteRes interface {
	refreshURLDocumentRouteRes()
}

type RegisterTwilioCallRes interface {
	registerTwilioCallRes()
}

type RemoveMemberRes interface {
	removeMemberRes()
}

type RemoveRulesRes interface {
	removeRulesRes()
}

type RenderRes interface {
	renderRes()
}

type RequestPvcManualVerificationRes interface {
	requestPvcManualVerificationRes()
}

type RetryBatchCallRes interface {
	retryBatchCallRes()
}

type RunConversationAnalysisRes interface {
	runConversationAnalysisRes()
}

type RunConversationEvaluationsRes interface {
	runConversationEvaluationsRes()
}

type RunPvcVoiceTrainingRes interface {
	runPvcVoiceTrainingRes()
}

type SearchGroupsRes interface {
	searchGroupsRes()
}

type SearchKnowledgeBaseContentRouteRes interface {
	searchKnowledgeBaseContentRouteRes()
}

type SeparateSongStemsRes interface {
	separateSongStemsRes()
}

type ShareResourceEndpointRes interface {
	shareResourceEndpointRes()
}

type SmartSearchConversationMessagesRouteRes interface {
	smartSearchConversationMessagesRouteRes()
}

type SoundGenerationRes interface {
	soundGenerationRes()
}

type SpeechToSpeechFullRes interface {
	speechToSpeechFullRes()
}

type SpeechToSpeechStreamRes interface {
	speechToSpeechStreamRes()
}

type SpeechToTextRes interface {
	speechToTextRes()
}

type StartSpeakerSeparationRes interface {
	startSpeakerSeparationRes()
}

type StreamChapterSnapshotAudioRes interface {
	streamChapterSnapshotAudioRes()
}

type StreamProjectSnapshotArchiveEndpointRes interface {
	streamProjectSnapshotArchiveEndpointRes()
}

type StreamProjectSnapshotAudioEndpointRes interface {
	streamProjectSnapshotAudioEndpointRes()
}

type TextSearchConversationMessagesRouteRes interface {
	textSearchConversationMessagesRouteRes()
}

type TextToDialogueFullWithTimestampsRes interface {
	textToDialogueFullWithTimestampsRes()
}

type TextToDialogueRes interface {
	textToDialogueRes()
}

type TextToDialogueStreamRes interface {
	textToDialogueStreamRes()
}

type TextToDialogueStreamWithTimestampsRes interface {
	textToDialogueStreamWithTimestampsRes()
}

type TextToSpeechFullRes interface {
	textToSpeechFullRes()
}

type TextToSpeechFullWithTimestampsRes interface {
	textToSpeechFullWithTimestampsRes()
}

type TextToSpeechStreamRes interface {
	textToSpeechStreamRes()
}

type TextToSpeechStreamWithTimestampsRes interface {
	textToSpeechStreamWithTimestampsRes()
}

type TextToVoiceDesignRes interface {
	textToVoiceDesignRes()
}

type TextToVoicePreviewStreamRes interface {
	textToVoicePreviewStreamRes()
}

type TextToVoiceRemixRes interface {
	textToVoiceRemixRes()
}

type TextToVoiceRes interface {
	textToVoiceRes()
}

type TranscribeRes interface {
	transcribeRes()
}

type TranslateRes interface {
	translateRes()
}

type UnassignConversationTagRouteRes interface {
	unassignConversationTagRouteRes()
}

type UnshareResourceEndpointRes interface {
	unshareResourceEndpointRes()
}

type UpdateAgentTestFolderRouteRes interface {
	updateAgentTestFolderRouteRes()
}

type UpdateBranchRouteRes interface {
	updateBranchRouteRes()
}

type UpdateConversationTagRouteRes interface {
	updateConversationTagRouteRes()
}

type UpdateDashboardSettingsRouteRes interface {
	updateDashboardSettingsRouteRes()
}

type UpdateDocumentRouteRes interface {
	updateDocumentRouteRes()
}

type UpdateFileDocumentRouteRes interface {
	updateFileDocumentRouteRes()
}

type UpdatePhoneNumberRouteRes interface {
	updatePhoneNumberRouteRes()
}

type UpdatePronunciationDictionariesRes interface {
	updatePronunciationDictionariesRes()
}

type UpdateSecretRouteRes interface {
	updateSecretRouteRes()
}

type UpdateSegmentLanguageRes interface {
	updateSegmentLanguageRes()
}

type UpdateSettingsRouteRes interface {
	updateSettingsRouteRes()
}

type UpdateSpeakerRes interface {
	updateSpeakerRes()
}

type UpdateWhatsappAccountRes interface {
	updateWhatsappAccountRes()
}

type UpdateWorkspaceMemberRes interface {
	updateWorkspaceMemberRes()
}

type UploadFileRouteRes interface {
	uploadFileRouteRes()
}

type UsageCharactersRes interface {
	usageCharactersRes()
}

type VerifyPvcVoiceCaptchaRes interface {
	verifyPvcVoiceCaptchaRes()
}

type VideoToMusicRes interface {
	videoToMusicRes()
}

type WhatsappOutboundCallRes interface {
	whatsappOutboundCallRes()
}

type WhatsappOutboundMessageRes interface {
	whatsappOutboundMessageRes()
}
