// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/go-faster/jx"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddDocumentationToKnowledgeBase implements add_documentation_to_knowledge_base operation.
	//
	// Uploads a file or reference a webpage to use as part of the shared knowledge base.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/convai/knowledge-base
	AddDocumentationToKnowledgeBase(ctx context.Context, req OptBodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostMultipart, params AddDocumentationToKnowledgeBaseParams) (AddDocumentationToKnowledgeBaseRes, error)
	// AddFromFile implements add_from_file operation.
	//
	// Creates a new pronunciation dictionary from a lexicon .PLS file.
	//
	// POST /v1/pronunciation-dictionaries/add-from-file
	AddFromFile(ctx context.Context, req *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostMultipart, params AddFromFileParams) (AddFromFileRes, error)
	// AddLanguage implements add_language operation.
	//
	// Adds the given ElevenLab Turbo V2/V2.5 language code to the resource. Does not automatically
	// generate transcripts/translations/audio.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/language
	AddLanguage(ctx context.Context, req *BodyAddALanguageToTheResourceV1DubbingResourceDubbingIDLanguagePost, params AddLanguageParams) (AddLanguageRes, error)
	// AddMember implements add_member operation.
	//
	// Adds a member of your workspace to the specified group. Requires `group_members_manage` permission.
	//
	// POST /v1/workspace/groups/{group_id}/members
	AddMember(ctx context.Context, req *BodyAddMemberToUserGroupV1WorkspaceGroupsGroupIDMembersPost, params AddMemberParams) (AddMemberRes, error)
	// AddProject implements add_project operation.
	//
	// Creates a new Studio project, it can be either initialized as blank, from a document or from a URL.
	//
	// POST /v1/studio/projects
	AddProject(ctx context.Context, req *BodyCreateStudioProjectV1StudioProjectsPostMultipart, params AddProjectParams) (AddProjectRes, error)
	// AddPvcVoiceSamples implements add_pvc_voice_samples operation.
	//
	// Add audio samples to a PVC voice.
	//
	// POST /v1/voices/pvc/{voice_id}/samples
	AddPvcVoiceSamples(ctx context.Context, req *BodyAddSamplesToPVCVoiceV1VoicesPvcVoiceIDSamplesPostMultipart, params AddPvcVoiceSamplesParams) (AddPvcVoiceSamplesRes, error)
	// AddSharingVoice implements add_sharing_voice operation.
	//
	// Add a shared voice to your collection of voices.
	//
	// POST /v1/voices/add/{public_user_id}/{voice_id}
	AddSharingVoice(ctx context.Context, req *BodyAddSharedVoiceV1VoicesAddPublicUserIDVoiceIDPost, params AddSharingVoiceParams) (AddSharingVoiceRes, error)
	// AddVoice implements add_voice operation.
	//
	// Add a new voice to your collection of voices in VoiceLab.
	//
	// POST /v1/voices/add
	AddVoice(ctx context.Context, req *BodyAddVoiceV1VoicesAddPostMultipart, params AddVoiceParams) (AddVoiceRes, error)
	// AgentTestingBulkMoveRoute implements agent_testing_bulk_move_route operation.
	//
	// Moves multiple tests or folders from one folder to another.
	//
	// POST /v1/convai/agent-testing/bulk-move
	AgentTestingBulkMoveRoute(ctx context.Context, req *BodyBulkMoveTestsToFolderV1ConvaiAgentTestingBulkMovePost, params AgentTestingBulkMoveRouteParams) (AgentTestingBulkMoveRouteRes, error)
	// AssignConversationTagsRoute implements assign_conversation_tags_route operation.
	//
	// Assign one or more conversation tags to a conversation. Tags that are already assigned are ignored.
	//  Tags must belong to the same workspace.
	//
	// POST /v1/convai/conversations/{conversation_id}/tags
	AssignConversationTagsRoute(ctx context.Context, req *AssignConversationTagsRequestModel, params AssignConversationTagsRouteParams) (AssignConversationTagsRouteRes, error)
	// AudioIsolation implements audio_isolation operation.
	//
	// Removes background noise from audio.
	//
	// POST /v1/audio-isolation
	AudioIsolation(ctx context.Context, req *BodyAudioIsolationV1AudioIsolationPostMultipart, params AudioIsolationParams) (AudioIsolationRes, error)
	// AudioIsolationStream implements audio_isolation_stream operation.
	//
	// Removes background noise from audio and streams the result.
	//
	// POST /v1/audio-isolation/stream
	AudioIsolationStream(ctx context.Context, req *BodyAudioIsolationStreamV1AudioIsolationStreamPostMultipart, params AudioIsolationStreamParams) (AudioIsolationStreamRes, error)
	// AudioNativeProjectUpdateContentEndpoint implements audio_native_project_update_content_endpoint operation.
	//
	// Updates content for the specific AudioNative Project.
	//
	// POST /v1/audio-native/{project_id}/content
	AudioNativeProjectUpdateContentEndpoint(ctx context.Context, req OptBodyUpdateAudioNativeProjectContentV1AudioNativeProjectIDContentPostMultipart, params AudioNativeProjectUpdateContentEndpointParams) (AudioNativeProjectUpdateContentEndpointRes, error)
	// AudioNativeUpdateContentFromURL implements audio_native_update_content_from_url operation.
	//
	// Finds an AudioNative project matching the provided URL, extracts content from the URL, updates the
	// project content, and queues it for conversion and auto-publishing.
	//
	// POST /v1/audio-native/content
	AudioNativeUpdateContentFromURL(ctx context.Context, req *BodyUpdateAudioNativeContentFromURLV1AudioNativeContentPost, params AudioNativeUpdateContentFromURLParams) (AudioNativeUpdateContentFromURLRes, error)
	// CancelBatchCall implements cancel_batch_call operation.
	//
	// Cancel a running batch call and set all recipients to cancelled status.
	//
	// POST /v1/convai/batch-calling/{batch_id}/cancel
	CancelBatchCall(ctx context.Context, params CancelBatchCallParams) (CancelBatchCallRes, error)
	// CancelFileUploadRoute implements cancel_file_upload_route operation.
	//
	// Remove a file upload from a conversation. Only possible if the file hasn't already been used in
	// the conversation.
	//
	// DELETE /v1/convai/conversations/{conversation_id}/files/{file_id}
	CancelFileUploadRoute(ctx context.Context, params CancelFileUploadRouteParams) (CancelFileUploadRouteRes, error)
	// ConvertChapterEndpoint implements convert_chapter_endpoint operation.
	//
	// Starts conversion of a specific chapter.
	//
	// POST /v1/studio/projects/{project_id}/chapters/{chapter_id}/convert
	ConvertChapterEndpoint(ctx context.Context, params ConvertChapterEndpointParams) (ConvertChapterEndpointRes, error)
	// ConvertProjectEndpoint implements convert_project_endpoint operation.
	//
	// Starts conversion of a Studio project and all of its chapters.
	//
	// POST /v1/studio/projects/{project_id}/convert
	ConvertProjectEndpoint(ctx context.Context, params ConvertProjectEndpointParams) (ConvertProjectEndpointRes, error)
	// CreateAgentDeploymentRoute implements create_agent_deployment_route operation.
	//
	// Create a new deployment for an agent.
	//
	// POST /v1/convai/agents/{agent_id}/deployments
	CreateAgentDeploymentRoute(ctx context.Context, req *BodyCreateOrUpdateDeploymentsV1ConvaiAgentsAgentIDDeploymentsPost, params CreateAgentDeploymentRouteParams) (CreateAgentDeploymentRouteRes, error)
	// CreateAgentTestFolderRoute implements create_agent_test_folder_route operation.
	//
	// Creates a folder for organizing agent tests.
	//
	// POST /v1/convai/agent-testing/folders
	CreateAgentTestFolderRoute(ctx context.Context, req *BodyCreateAgentTestFolderV1ConvaiAgentTestingFoldersPost, params CreateAgentTestFolderRouteParams) (CreateAgentTestFolderRouteRes, error)
	// CreateAudioNativeProject implements create_audio_native_project operation.
	//
	// Creates Audio Native enabled project, optionally starts conversion and returns project ID and
	// embeddable HTML snippet.
	//
	// POST /v1/audio-native
	CreateAudioNativeProject(ctx context.Context, req *BodyCreatesAudioNativeEnabledProjectV1AudioNativePostMultipart, params CreateAudioNativeProjectParams) (CreateAudioNativeProjectRes, error)
	// CreateBatchCall implements create_batch_call operation.
	//
	// Submit a batch call request to schedule calls for multiple recipients.
	//
	// POST /v1/convai/batch-calling/submit
	CreateBatchCall(ctx context.Context, req *BodySubmitABatchCallRequestV1ConvaiBatchCallingSubmitPost, params CreateBatchCallParams) (CreateBatchCallRes, error)
	// CreateClip implements create_clip operation.
	//
	// Creates a new segment in dubbing resource with a start and end time for the speaker in every
	// available language. Does not automatically generate transcripts/translations/audio.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}/segment
	CreateClip(ctx context.Context, req *SegmentCreatePayload, params CreateClipParams) (CreateClipRes, error)
	// CreateConversationTagRoute implements create_conversation_tag_route operation.
	//
	// Create a new conversation tag for the workspace.
	//
	// POST /v1/convai/tags
	CreateConversationTagRoute(ctx context.Context, req *CreateConversationTagRequestModel, params CreateConversationTagRouteParams) (CreateConversationTagRouteRes, error)
	// CreateDubbing implements create_dubbing operation.
	//
	// Dubs a provided audio or video file into given language.
	//
	// POST /v1/dubbing
	CreateDubbing(ctx context.Context, req OptBodyDubAVideoOrAnAudioFileV1DubbingPostMultipart, params CreateDubbingParams) (CreateDubbingRes, error)
	// CreateFileDocumentRoute implements create_file_document_route operation.
	//
	// Create a knowledge base document generated form the uploaded file.
	//
	// POST /v1/convai/knowledge-base/file
	CreateFileDocumentRoute(ctx context.Context, req *BodyCreateFileDocumentV1ConvaiKnowledgeBaseFilePostMultipart, params CreateFileDocumentRouteParams) (CreateFileDocumentRouteRes, error)
	// CreateFolderRoute implements create_folder_route operation.
	//
	// Create a folder used for grouping documents together.
	//
	// POST /v1/convai/knowledge-base/folder
	CreateFolderRoute(ctx context.Context, req *BodyCreateFolderV1ConvaiKnowledgeBaseFolderPost, params CreateFolderRouteParams) (CreateFolderRouteRes, error)
	// CreatePvcVoice implements create_pvc_voice operation.
	//
	// Creates a new PVC voice with metadata but no samples.
	//
	// POST /v1/voices/pvc
	CreatePvcVoice(ctx context.Context, req *BodyCreatePVCVoiceV1VoicesPvcPost, params CreatePvcVoiceParams) (CreatePvcVoiceRes, error)
	// CreateSecretRoute implements create_secret_route operation.
	//
	// Create a new secret for the workspace.
	//
	// POST /v1/convai/secrets
	CreateSecretRoute(ctx context.Context, req *PostWorkspaceSecretRequest, params CreateSecretRouteParams) (CreateSecretRouteRes, error)
	// CreateServiceAccountAPIKey implements create_service_account_api_key operation.
	//
	// Create a new API key for a service account.
	//
	// POST /v1/service-accounts/{service_account_user_id}/api-keys
	CreateServiceAccountAPIKey(ctx context.Context, req *BodyCreateServiceAccountAPIKeyV1ServiceAccountsServiceAccountUserIDAPIKeysPost, params CreateServiceAccountAPIKeyParams) (CreateServiceAccountAPIKeyRes, error)
	// CreateSpeaker implements create_speaker operation.
	//
	// Create A New Speaker.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/speaker
	CreateSpeaker(ctx context.Context, req OptBodyCreateANewSpeakerV1DubbingResourceDubbingIDSpeakerPost, params CreateSpeakerParams) (CreateSpeakerRes, error)
	// CreateTextDocumentRoute implements create_text_document_route operation.
	//
	// Create a knowledge base document containing the provided text.
	//
	// POST /v1/convai/knowledge-base/text
	CreateTextDocumentRoute(ctx context.Context, req *BodyCreateTextDocumentV1ConvaiKnowledgeBaseTextPost, params CreateTextDocumentRouteParams) (CreateTextDocumentRouteRes, error)
	// CreateURLDocumentRoute implements create_url_document_route operation.
	//
	// Create a knowledge base document generated by scraping the given webpage.
	//
	// POST /v1/convai/knowledge-base/url
	CreateURLDocumentRoute(ctx context.Context, req *BodyCreateURLDocumentV1ConvaiKnowledgeBaseURLPost, params CreateURLDocumentRouteParams) (CreateURLDocumentRouteRes, error)
	// CreateVoice implements create_voice operation.
	//
	// Create a voice from previously generated voice preview. This endpoint should be called after you
	// fetched a generated_voice_id using POST /v1/text-to-voice/design or POST
	// /v1/text-to-voice/:voice_id/remix.
	//
	// POST /v1/text-to-voice
	CreateVoice(ctx context.Context, req *BodyCreateANewVoiceFromVoicePreviewV1TextToVoicePost, params CreateVoiceParams) (CreateVoiceRes, error)
	// CreateWorkspaceWebhookRoute implements create_workspace_webhook_route operation.
	//
	// Create a new webhook for the workspace with the specified authentication type.
	//
	// POST /v1/workspace/webhooks
	CreateWorkspaceWebhookRoute(ctx context.Context, req *BodyCreateWorkspaceWebhookV1WorkspaceWebhooksPost, params CreateWorkspaceWebhookRouteParams) (CreateWorkspaceWebhookRouteRes, error)
	// DeleteAgentDraftRoute implements delete_agent_draft_route operation.
	//
	// Delete a draft for an agent.
	//
	// DELETE /v1/convai/agents/{agent_id}/drafts
	DeleteAgentDraftRoute(ctx context.Context, params DeleteAgentDraftRouteParams) (DeleteAgentDraftRouteRes, error)
	// DeleteAgentRoute implements delete_agent_route operation.
	//
	// Delete an agent.
	//
	// DELETE /v1/convai/agents/{agent_id}
	DeleteAgentRoute(ctx context.Context, params DeleteAgentRouteParams) (DeleteAgentRouteRes, error)
	// DeleteAgentTestFolderRoute implements delete_agent_test_folder_route operation.
	//
	// Deletes an agent test folder by ID. Use force=true to delete a non-empty folder and all its
	// contents.
	//
	// DELETE /v1/convai/agent-testing/folders/{folder_id}
	DeleteAgentTestFolderRoute(ctx context.Context, params DeleteAgentTestFolderRouteParams) (DeleteAgentTestFolderRouteRes, error)
	// DeleteAudioIsolationHistoryItem implements delete_audio_isolation_history_item operation.
	//
	// Deletes a specific audio isolation history item and the associated media files.
	//
	// DELETE /v1/audio-isolation/history/{history_item_id}
	DeleteAudioIsolationHistoryItem(ctx context.Context, params DeleteAudioIsolationHistoryItemParams) (DeleteAudioIsolationHistoryItemRes, error)
	// DeleteAuthConnection implements delete_auth_connection operation.
	//
	// Delete an auth connection.
	//
	// DELETE /v1/workspace/auth-connections/{auth_connection_id}
	DeleteAuthConnection(ctx context.Context, params DeleteAuthConnectionParams) (DeleteAuthConnectionRes, error)
	// DeleteBatchCall implements delete_batch_call operation.
	//
	// Permanently delete a batch call and all recipient records. Conversations remain in history.
	//
	// DELETE /v1/convai/batch-calling/{batch_id}
	DeleteBatchCall(ctx context.Context, params DeleteBatchCallParams) (DeleteBatchCallRes, error)
	// DeleteChapterEndpoint implements delete_chapter_endpoint operation.
	//
	// Deletes a chapter.
	//
	// DELETE /v1/studio/projects/{project_id}/chapters/{chapter_id}
	DeleteChapterEndpoint(ctx context.Context, params DeleteChapterEndpointParams) (DeleteChapterEndpointRes, error)
	// DeleteChatResponseTestRoute implements delete_chat_response_test_route operation.
	//
	// Deletes an agent response test by ID.
	//
	// DELETE /v1/convai/agent-testing/{test_id}
	DeleteChatResponseTestRoute(ctx context.Context, params DeleteChatResponseTestRouteParams) (DeleteChatResponseTestRouteRes, error)
	// DeleteConversationRoute implements delete_conversation_route operation.
	//
	// Delete a particular conversation.
	//
	// DELETE /v1/convai/conversations/{conversation_id}
	DeleteConversationRoute(ctx context.Context, params DeleteConversationRouteParams) (DeleteConversationRouteRes, error)
	// DeleteConversationTagRoute implements delete_conversation_tag_route operation.
	//
	// Delete a conversation tag. Restricted to the tag owner or a workspace admin.
	//
	// DELETE /v1/convai/tags/{tag_id}
	DeleteConversationTagRoute(ctx context.Context, params DeleteConversationTagRouteParams) (DeleteConversationTagRouteRes, error)
	// DeleteDubbing implements delete_dubbing operation.
	//
	// Deletes a dubbing project.
	//
	// DELETE /v1/dubbing/{dubbing_id}
	DeleteDubbing(ctx context.Context, params DeleteDubbingParams) (DeleteDubbingRes, error)
	// DeleteInvite implements delete_invite operation.
	//
	// Invalidates an existing email invitation. The invitation will still show up in the inbox it has
	// been delivered to, but activating it to join the workspace won't work. This endpoint may only be
	// called by workspace members with the WORKSPACE_MEMBERS_INVITE permission.
	//
	// DELETE /v1/workspace/invites
	DeleteInvite(ctx context.Context, req *BodyDeleteExistingInvitationV1WorkspaceInvitesDelete, params DeleteInviteParams) (DeleteInviteRes, error)
	// DeleteKnowledgeBaseDocument implements delete_knowledge_base_document operation.
	//
	// Delete a document or folder from the knowledge base.
	//
	// DELETE /v1/convai/knowledge-base/{documentation_id}
	DeleteKnowledgeBaseDocument(ctx context.Context, params DeleteKnowledgeBaseDocumentParams) (DeleteKnowledgeBaseDocumentRes, error)
	// DeleteMcpServerRoute implements delete_mcp_server_route operation.
	//
	// Delete a specific MCP server configuration from the workspace.
	//
	// DELETE /v1/convai/mcp-servers/{mcp_server_id}
	DeleteMcpServerRoute(ctx context.Context, params DeleteMcpServerRouteParams) (DeleteMcpServerRouteRes, error)
	// DeletePhoneNumberRoute implements delete_phone_number_route operation.
	//
	// Delete Phone Number by ID.
	//
	// DELETE /v1/convai/phone-numbers/{phone_number_id}
	DeletePhoneNumberRoute(ctx context.Context, params DeletePhoneNumberRouteParams) (DeletePhoneNumberRouteRes, error)
	// DeleteProject implements delete_project operation.
	//
	// Deletes a Studio project.
	//
	// DELETE /v1/studio/projects/{project_id}
	DeleteProject(ctx context.Context, params DeleteProjectParams) (DeleteProjectRes, error)
	// DeletePvcVoiceSample implements delete_pvc_voice_sample operation.
	//
	// Delete a sample from a PVC voice.
	//
	// DELETE /v1/voices/pvc/{voice_id}/samples/{sample_id}
	DeletePvcVoiceSample(ctx context.Context, params DeletePvcVoiceSampleParams) (DeletePvcVoiceSampleRes, error)
	// DeleteRagIndex implements delete_rag_index operation.
	//
	// Delete RAG index for the knowledgebase document.
	//
	// DELETE /v1/convai/knowledge-base/{documentation_id}/rag-index/{rag_index_id}
	DeleteRagIndex(ctx context.Context, params DeleteRagIndexParams) (DeleteRagIndexRes, error)
	// DeleteSample implements delete_sample operation.
	//
	// Removes a sample by its ID.
	//
	// DELETE /v1/voices/{voice_id}/samples/{sample_id}
	DeleteSample(ctx context.Context, params DeleteSampleParams) (DeleteSampleRes, error)
	// DeleteSecretRoute implements delete_secret_route operation.
	//
	// Delete a workspace secret if it's not in use.
	//
	// DELETE /v1/convai/secrets/{secret_id}
	DeleteSecretRoute(ctx context.Context, params DeleteSecretRouteParams) (DeleteSecretRouteRes, error)
	// DeleteSegment implements delete_segment operation.
	//
	// Deletes a single segment from the dubbing.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /v1/dubbing/resource/{dubbing_id}/segment/{segment_id}
	DeleteSegment(ctx context.Context, params DeleteSegmentParams) (DeleteSegmentRes, error)
	// DeleteServiceAccountAPIKey implements delete_service_account_api_key operation.
	//
	// Delete an existing API key for a service account.
	//
	// DELETE /v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}
	DeleteServiceAccountAPIKey(ctx context.Context, params DeleteServiceAccountAPIKeyParams) (DeleteServiceAccountAPIKeyRes, error)
	// DeleteSpeechEngine implements delete_speech_engine operation.
	//
	// Delete a Speech Engine resource.
	//
	// DELETE /v1/speech-engine/{speech_engine_id}
	DeleteSpeechEngine(ctx context.Context, params DeleteSpeechEngineParams) (DeleteSpeechEngineRes, error)
	// DeleteSpeechHistoryItem implements delete_speech_history_item operation.
	//
	// Delete a history item by its ID.
	//
	// DELETE /v1/history/{history_item_id}
	DeleteSpeechHistoryItem(ctx context.Context, params DeleteSpeechHistoryItemParams) (DeleteSpeechHistoryItemRes, error)
	// DeleteToolRoute implements delete_tool_route operation.
	//
	// Delete tool from the workspace.
	//
	// DELETE /v1/convai/tools/{tool_id}
	DeleteToolRoute(ctx context.Context, params DeleteToolRouteParams) (DeleteToolRouteRes, error)
	// DeleteTranscriptByID implements delete_transcript_by_id operation.
	//
	// Delete a previously generated transcript by its ID.
	//
	// DELETE /v1/speech-to-text/transcripts/{transcription_id}
	DeleteTranscriptByID(ctx context.Context, params DeleteTranscriptByIDParams) (DeleteTranscriptByIDRes, error)
	// DeleteVoice implements delete_voice operation.
	//
	// Deletes a voice by its ID.
	//
	// DELETE /v1/voices/{voice_id}
	DeleteVoice(ctx context.Context, params DeleteVoiceParams) (DeleteVoiceRes, error)
	// DeleteWhatsappAccount implements delete_whatsapp_account operation.
	//
	// Delete a WhatsApp account.
	//
	// DELETE /v1/convai/whatsapp-accounts/{phone_number_id}
	DeleteWhatsappAccount(ctx context.Context, params DeleteWhatsappAccountParams) (DeleteWhatsappAccountRes, error)
	// DeleteWorkspaceWebhookRoute implements delete_workspace_webhook_route operation.
	//
	// Delete the specified workspace webhook.
	//
	// DELETE /v1/workspace/webhooks/{webhook_id}
	DeleteWorkspaceWebhookRoute(ctx context.Context, params DeleteWorkspaceWebhookRouteParams) (DeleteWorkspaceWebhookRouteRes, error)
	// Disable implements disable operation.
	//
	// Disable the API key used to authenticate this request. Requires the query parameter
	// `api_key_name=self` as an explicit confirmation. This endpoint requires additional permissions and
	// is not enabled by default. Reach out to your ElevenLabs contact to request access.
	//
	// POST /v1/workspaces/api-keys/disable
	Disable(ctx context.Context, params DisableParams) (DisableRes, error)
	// DownloadSpeechHistoryItems implements download_speech_history_items operation.
	//
	// Download one or more history items. If one history item ID is provided, we will return a single
	// audio file. If more than one history item IDs are provided, we will provide the history items
	// packed into a .zip file.
	//
	// POST /v1/history/download
	DownloadSpeechHistoryItems(ctx context.Context, req *BodyDownloadHistoryItemsV1HistoryDownloadPost, params DownloadSpeechHistoryItemsParams) (DownloadSpeechHistoryItemsRes, error)
	// Dub implements dub operation.
	//
	// Regenerate the dubs for either the entire resource or the specified segments/languages. Will
	// automatically transcribe and translate any missing transcriptions and translations.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/dub
	Dub(ctx context.Context, req *BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDDubPost, params DubParams) (DubRes, error)
	// DuplicateAgentRoute implements duplicate_agent_route operation.
	//
	// Create a new agent by duplicating an existing one.
	//
	// POST /v1/convai/agents/{agent_id}/duplicate
	DuplicateAgentRoute(ctx context.Context, req OptBodyDuplicateAgentV1ConvaiAgentsAgentIDDuplicatePost, params DuplicateAgentRouteParams) (DuplicateAgentRouteRes, error)
	// EditProject implements edit_project operation.
	//
	// Updates the specified Studio project by setting the values of the parameters passed.
	//
	// POST /v1/studio/projects/{project_id}
	EditProject(ctx context.Context, req *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost, params EditProjectParams) (EditProjectRes, error)
	// EditProjectContent implements edit_project_content operation.
	//
	// Updates Studio project content.
	//
	// POST /v1/studio/projects/{project_id}/content
	EditProjectContent(ctx context.Context, req OptBodyUpdateStudioProjectContentV1StudioProjectsProjectIDContentPostMultipart, params EditProjectContentParams) (EditProjectContentRes, error)
	// EditPvcVoice implements edit_pvc_voice operation.
	//
	// Edit PVC voice metadata.
	//
	// POST /v1/voices/pvc/{voice_id}
	EditPvcVoice(ctx context.Context, req OptBodyEditPVCVoiceV1VoicesPvcVoiceIDPost, params EditPvcVoiceParams) (EditPvcVoiceRes, error)
	// EditPvcVoiceSample implements edit_pvc_voice_sample operation.
	//
	// Update a PVC voice sample - apply noise removal, select speaker, change trim times or file name.
	//
	// POST /v1/voices/pvc/{voice_id}/samples/{sample_id}
	EditPvcVoiceSample(ctx context.Context, req OptBodyUpdatePVCVoiceSampleV1VoicesPvcVoiceIDSamplesSampleIDPost, params EditPvcVoiceSampleParams) (EditPvcVoiceSampleRes, error)
	// EditServiceAccountAPIKey implements edit_service_account_api_key operation.
	//
	// Update an existing API key for a service account.
	//
	// PATCH /v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}
	EditServiceAccountAPIKey(ctx context.Context, req OptBodyEditServiceAccountAPIKeyV1ServiceAccountsServiceAccountUserIDAPIKeysAPIKeyIDPatch, params EditServiceAccountAPIKeyParams) (EditServiceAccountAPIKeyRes, error)
	// EditVoice implements edit_voice operation.
	//
	// Edit a voice created by you.
	//
	// POST /v1/voices/{voice_id}/edit
	EditVoice(ctx context.Context, req *BodyEditVoiceV1VoicesVoiceIDEditPostMultipart, params EditVoiceParams) (EditVoiceRes, error)
	// EditVoiceSettings implements edit_voice_settings operation.
	//
	// Edit your settings for a specific voice. "similarity_boost" corresponds to "Clarity + Similarity
	// Enhancement" in the web app and "stability" corresponds to "Stability" slider in the web app.
	//
	// POST /v1/voices/{voice_id}/settings/edit
	EditVoiceSettings(ctx context.Context, req *VoiceSettingsResponseModel, params EditVoiceSettingsParams) (EditVoiceSettingsRes, error)
	// EditWorkspaceWebhookRoute implements edit_workspace_webhook_route operation.
	//
	// Update the specified workspace webhook.
	//
	// PATCH /v1/workspace/webhooks/{webhook_id}
	EditWorkspaceWebhookRoute(ctx context.Context, req *BodyUpdateWorkspaceWebhookV1WorkspaceWebhooksWebhookIDPatch, params EditWorkspaceWebhookRouteParams) (EditWorkspaceWebhookRouteRes, error)
	// ForcedAlignment implements forced_alignment operation.
	//
	// Force align an audio file to text. Use this endpoint to get the timing information for each
	// character and word in an audio file based on a provided text transcript.
	//
	// POST /v1/forced-alignment
	ForcedAlignment(ctx context.Context, req *BodyCreateForcedAlignmentV1ForcedAlignmentPostMultipart, params ForcedAlignmentParams) (ForcedAlignmentRes, error)
	// GetAgentKnowledgeBaseSize implements get_agent_knowledge_base_size operation.
	//
	// Returns the number of pages in the agent's knowledge base.
	//
	// GET /v1/convai/agent/{agent_id}/knowledge-base/size
	GetAgentKnowledgeBaseSize(ctx context.Context, params GetAgentKnowledgeBaseSizeParams) (GetAgentKnowledgeBaseSizeRes, error)
	// GetAgentKnowledgeBaseSummariesRoute implements get_agent_knowledge_base_summaries_route operation.
	//
	// Gets multiple knowledge base document summaries by their IDs.
	//
	// GET /v1/convai/knowledge-base/summaries
	GetAgentKnowledgeBaseSummariesRoute(ctx context.Context, params GetAgentKnowledgeBaseSummariesRouteParams) (GetAgentKnowledgeBaseSummariesRouteRes, error)
	// GetAgentLinkRoute implements get_agent_link_route operation.
	//
	// Get the current link used to share the agent with others.
	//
	// GET /v1/convai/agents/{agent_id}/link
	GetAgentLinkRoute(ctx context.Context, params GetAgentLinkRouteParams) (GetAgentLinkRouteRes, error)
	// GetAgentLlmExpectedCostCalculation implements get_agent_llm_expected_cost_calculation operation.
	//
	// Calculates expected number of LLM tokens needed for the specified agent.
	//
	// POST /v1/convai/agent/{agent_id}/llm-usage/calculate
	GetAgentLlmExpectedCostCalculation(ctx context.Context, req *LLMUsageCalculatorRequestModel, params GetAgentLlmExpectedCostCalculationParams) (GetAgentLlmExpectedCostCalculationRes, error)
	// GetAgentResponseTestRoute implements get_agent_response_test_route operation.
	//
	// Gets an agent response test by ID.
	//
	// GET /v1/convai/agent-testing/{test_id}
	GetAgentResponseTestRoute(ctx context.Context, params GetAgentResponseTestRouteParams) (GetAgentResponseTestRouteRes, error)
	// GetAgentResponseTestsSummariesRoute implements get_agent_response_tests_summaries_route operation.
	//
	// Gets multiple agent response tests by their IDs. Returns a dictionary mapping test IDs to test
	// summaries.
	//
	// POST /v1/convai/agent-testing/summaries
	GetAgentResponseTestsSummariesRoute(ctx context.Context, req *ListTestsByIdsRequestModel, params GetAgentResponseTestsSummariesRouteParams) (GetAgentResponseTestsSummariesRouteRes, error)
	// GetAgentSummariesRoute implements get_agent_summaries_route operation.
	//
	// Returns summaries for the specified agents.
	//
	// GET /v1/convai/agents/summaries
	GetAgentSummariesRoute(ctx context.Context, params GetAgentSummariesRouteParams) (GetAgentSummariesRouteRes, error)
	// GetAgentTestFolderRoute implements get_agent_test_folder_route operation.
	//
	// Gets an agent test folder by ID, including its folder path.
	//
	// GET /v1/convai/agent-testing/folders/{folder_id}
	GetAgentTestFolderRoute(ctx context.Context, params GetAgentTestFolderRouteParams) (GetAgentTestFolderRouteRes, error)
	// GetAgentTopicsRoute implements get_agent_topics_route operation.
	//
	// Returns the latest topic discovery run results for a given agent.
	//
	// GET /v1/convai/agents/{agent_id}/topics
	GetAgentTopicsRoute(ctx context.Context, params GetAgentTopicsRouteParams) (GetAgentTopicsRouteRes, error)
	// GetAgentsRoute implements get_agents_route operation.
	//
	// Returns a list of your agents and their metadata.
	//
	// GET /v1/convai/agents
	GetAgentsRoute(ctx context.Context, params GetAgentsRouteParams) (GetAgentsRouteRes, error)
	// GetAudioFromSample implements get_audio_from_sample operation.
	//
	// Returns the audio corresponding to a sample attached to a voice.
	//
	// GET /v1/voices/{voice_id}/samples/{sample_id}/audio
	GetAudioFromSample(ctx context.Context, params GetAudioFromSampleParams) (GetAudioFromSampleRes, error)
	// GetAudioFullFromSpeechHistoryItem implements get_audio_full_from_speech_history_item operation.
	//
	// Returns the audio of an history item.
	//
	// GET /v1/history/{history_item_id}/audio
	GetAudioFullFromSpeechHistoryItem(ctx context.Context, params GetAudioFullFromSpeechHistoryItemParams) (GetAudioFullFromSpeechHistoryItemRes, error)
	// GetAudioIsolationHistory implements get_audio_isolation_history operation.
	//
	// Returns a list of all your audio isolation generations.
	//
	// GET /v1/audio-isolation/history
	GetAudioIsolationHistory(ctx context.Context, params GetAudioIsolationHistoryParams) (GetAudioIsolationHistoryRes, error)
	// GetAudioNativeProjectSettingsEndpoint implements get_audio_native_project_settings_endpoint operation.
	//
	// Get player settings for the specific project.
	//
	// GET /v1/audio-native/{project_id}/settings
	GetAudioNativeProjectSettingsEndpoint(ctx context.Context, params GetAudioNativeProjectSettingsEndpointParams) (GetAudioNativeProjectSettingsEndpointRes, error)
	// GetBatchCall implements get_batch_call operation.
	//
	// Get detailed information about a batch call including all recipients.
	//
	// GET /v1/convai/batch-calling/{batch_id}
	GetBatchCall(ctx context.Context, params GetBatchCallParams) (GetBatchCallRes, error)
	// GetBranchRoute implements get_branch_route operation.
	//
	// Get information about a single agent branch.
	//
	// GET /v1/convai/agents/{agent_id}/branches/{branch_id}
	GetBranchRoute(ctx context.Context, params GetBranchRouteParams) (GetBranchRouteRes, error)
	// GetBranchesRoute implements get_branches_route operation.
	//
	// Returns a list of branches an agent has.
	//
	// GET /v1/convai/agents/{agent_id}/branches
	GetBranchesRoute(ctx context.Context, params GetBranchesRouteParams) (GetBranchesRouteRes, error)
	// GetChapterSnapshotEndpoint implements get_chapter_snapshot_endpoint operation.
	//
	// Returns the chapter snapshot.
	//
	// GET /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots/{chapter_snapshot_id}
	GetChapterSnapshotEndpoint(ctx context.Context, params GetChapterSnapshotEndpointParams) (GetChapterSnapshotEndpointRes, error)
	// GetChapterSnapshots implements get_chapter_snapshots operation.
	//
	// Gets information about all the snapshots of a chapter. Each snapshot can be downloaded as audio.
	// Whenever a chapter is converted a snapshot will automatically be created.
	//
	// GET /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots
	GetChapterSnapshots(ctx context.Context, params GetChapterSnapshotsParams) (GetChapterSnapshotsRes, error)
	// GetChapters implements get_chapters operation.
	//
	// Returns a list of a Studio project's chapters.
	//
	// GET /v1/studio/projects/{project_id}/chapters
	GetChapters(ctx context.Context, params GetChaptersParams) (GetChaptersRes, error)
	// GetConversationAudioRoute implements get_conversation_audio_route operation.
	//
	// Get the audio recording of a particular conversation.
	//
	// GET /v1/convai/conversations/{conversation_id}/audio
	GetConversationAudioRoute(ctx context.Context, params GetConversationAudioRouteParams) (GetConversationAudioRouteRes, error)
	// GetConversationHistoriesRoute implements get_conversation_histories_route operation.
	//
	// Get all conversations of agents that user owns. With option to restrict to a specific agent.
	//
	// GET /v1/convai/conversations
	GetConversationHistoriesRoute(ctx context.Context, params GetConversationHistoriesRouteParams) (GetConversationHistoriesRouteRes, error)
	// GetConversationHistoryRoute implements get_conversation_history_route operation.
	//
	// Get the details of a particular conversation.
	//
	// GET /v1/convai/conversations/{conversation_id}
	GetConversationHistoryRoute(ctx context.Context, params GetConversationHistoryRouteParams) (GetConversationHistoryRouteRes, error)
	// GetConversationSignedLink implements get_conversation_signed_link operation.
	//
	// Get a signed url to start a conversation with an agent with an agent that requires authorization.
	//
	// GET /v1/convai/conversation/get-signed-url
	GetConversationSignedLink(ctx context.Context, params GetConversationSignedLinkParams) (GetConversationSignedLinkRes, error)
	// GetConversationSipMessages implements get_conversation_sip_messages operation.
	//
	// Get SIP messages associated with a conversation's phone call.
	//
	// GET /v1/convai/conversations/{conversation_id}/sip-messages
	GetConversationSipMessages(ctx context.Context, params GetConversationSipMessagesParams) (GetConversationSipMessagesRes, error)
	// GetConversationTagRoute implements get_conversation_tag_route operation.
	//
	// Get a conversation tag by ID.
	//
	// GET /v1/convai/tags/{tag_id}
	GetConversationTagRoute(ctx context.Context, params GetConversationTagRouteParams) (GetConversationTagRouteRes, error)
	// GetConversationUsersRoute implements get_conversation_users_route operation.
	//
	// Get distinct users from conversations with pagination.
	//
	// GET /v1/convai/users
	GetConversationUsersRoute(ctx context.Context, params GetConversationUsersRouteParams) (GetConversationUsersRouteRes, error)
	// GetDashboardSettingsRoute implements get_dashboard_settings_route operation.
	//
	// Retrieve Convai dashboard settings for the workspace.
	//
	// GET /v1/convai/settings/dashboard
	GetDashboardSettingsRoute(ctx context.Context, params GetDashboardSettingsRouteParams) (GetDashboardSettingsRouteRes, error)
	// GetDocumentationChunkFromKnowledgeBase implements get_documentation_chunk_from_knowledge_base operation.
	//
	// Get details about a specific documentation part used by RAG.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}/chunk/{chunk_id}
	GetDocumentationChunkFromKnowledgeBase(ctx context.Context, params GetDocumentationChunkFromKnowledgeBaseParams) (GetDocumentationChunkFromKnowledgeBaseRes, error)
	// GetDocumentationChunksFromKnowledgeBase implements get_documentation_chunks_from_knowledge_base operation.
	//
	// Get all RAG chunks for a specific knowledge base document.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}/chunks
	GetDocumentationChunksFromKnowledgeBase(ctx context.Context, params GetDocumentationChunksFromKnowledgeBaseParams) (GetDocumentationChunksFromKnowledgeBaseRes, error)
	// GetDocumentationFromKnowledgeBase implements get_documentation_from_knowledge_base operation.
	//
	// Get details about a specific documentation making up the agent's knowledge base.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}
	GetDocumentationFromKnowledgeBase(ctx context.Context, params GetDocumentationFromKnowledgeBaseParams) (GetDocumentationFromKnowledgeBaseRes, error)
	// GetDubbedFile implements get_dubbed_file operation.
	//
	// Returns dub as a streamed MP3 or MP4 file. If this dub has been edited using Dubbing Studio you
	// need to use the resource render endpoint as this endpoint only returns the original automatic dub
	// result.
	//
	// GET /v1/dubbing/{dubbing_id}/audio/{language_code}
	GetDubbedFile(ctx context.Context, params GetDubbedFileParams) (GetDubbedFileRes, error)
	// GetDubbedMetadata implements get_dubbed_metadata operation.
	//
	// Returns metadata about a dubbing project, including whether it's still in progress or not.
	//
	// GET /v1/dubbing/{dubbing_id}
	GetDubbedMetadata(ctx context.Context, params GetDubbedMetadataParams) (GetDubbedMetadataRes, error)
	// GetDubbedTranscriptFile implements get_dubbed_transcript_file operation.
	//
	// Returns transcript for the dub as an SRT or WEBVTT file.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/dubbing/{dubbing_id}/transcript/{language_code}
	GetDubbedTranscriptFile(ctx context.Context, params GetDubbedTranscriptFileParams) (GetDubbedTranscriptFileRes, error)
	// GetDubbingResource implements get_dubbing_resource operation.
	//
	// Given a dubbing ID generated from the '/v1/dubbing' endpoint with studio enabled, returns the
	// dubbing resource.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/dubbing/resource/{dubbing_id}
	GetDubbingResource(ctx context.Context, params GetDubbingResourceParams) (GetDubbingResourceRes, error)
	// GetDubbingTranscripts implements get_dubbing_transcripts operation.
	//
	// Fetch the transcript for one of the languages in a dub.
	//
	// GET /v1/dubbing/{dubbing_id}/transcripts/{language_code}/format/{format_type}
	GetDubbingTranscripts(ctx context.Context, params GetDubbingTranscriptsParams) (GetDubbingTranscriptsRes, error)
	// GetGroupsEndpoint implements get_groups_endpoint operation.
	//
	// Get all groups in the workspace.
	//
	// GET /v1/workspace/groups
	GetGroupsEndpoint(ctx context.Context, params GetGroupsEndpointParams) (GetGroupsEndpointRes, error)
	// GetKnowledgeBaseContent implements get_knowledge_base_content operation.
	//
	// Get the entire content of a document from the knowledge base.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}/content
	GetKnowledgeBaseContent(ctx context.Context, params GetKnowledgeBaseContentParams) (GetKnowledgeBaseContentRes, error)
	// GetKnowledgeBaseDependentAgents implements get_knowledge_base_dependent_agents operation.
	//
	// Get a list of agents depending on this knowledge base document.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}/dependent-agents
	GetKnowledgeBaseDependentAgents(ctx context.Context, params GetKnowledgeBaseDependentAgentsParams) (GetKnowledgeBaseDependentAgentsRes, error)
	// GetKnowledgeBaseListRoute implements get_knowledge_base_list_route operation.
	//
	// Get a list of available knowledge base documents.
	//
	// GET /v1/convai/knowledge-base
	GetKnowledgeBaseListRoute(ctx context.Context, params GetKnowledgeBaseListRouteParams) (GetKnowledgeBaseListRouteRes, error)
	// GetKnowledgeBaseSourceFileURL implements get_knowledge_base_source_file_url operation.
	//
	// Get a signed URL to download the original source file of a file-type document from the knowledge
	// base.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}/source-file-url
	GetKnowledgeBaseSourceFileURL(ctx context.Context, params GetKnowledgeBaseSourceFileURLParams) (GetKnowledgeBaseSourceFileURLRes, error)
	// GetLibraryVoices implements get_library_voices operation.
	//
	// Retrieves a list of shared voices.
	//
	// GET /v1/shared-voices
	GetLibraryVoices(ctx context.Context, params GetLibraryVoicesParams) (GetLibraryVoicesRes, error)
	// GetLiveCount implements get_live_count operation.
	//
	// Get the live count of the ongoing conversations.
	//
	// GET /v1/convai/analytics/live-count
	GetLiveCount(ctx context.Context, params GetLiveCountParams) (GetLiveCountRes, error)
	// GetLivekitToken implements get_livekit_token operation.
	//
	// Get a WebRTC session token for real-time communication.
	//
	// GET /v1/convai/conversation/token
	GetLivekitToken(ctx context.Context, params GetLivekitTokenParams) (GetLivekitTokenRes, error)
	// GetMcpToolConfigOverrideRoute implements get_mcp_tool_config_override_route operation.
	//
	// Retrieve configuration overrides for a specific MCP tool.
	//
	// GET /v1/convai/mcp-servers/{mcp_server_id}/tool-configs/{tool_name}
	GetMcpToolConfigOverrideRoute(ctx context.Context, params GetMcpToolConfigOverrideRouteParams) (GetMcpToolConfigOverrideRouteRes, error)
	// GetModels implements get_models operation.
	//
	// Gets a list of available models.
	//
	// GET /v1/models
	GetModels(ctx context.Context, params GetModelsParams) (GetModelsRes, error)
	// GetOrCreateRagIndexes implements get_or_create_rag_indexes operation.
	//
	// Retrieves and/or creates RAG indexes for multiple knowledge base documents in a single request.
	// Maximum 100 items per request.
	//
	// POST /v1/convai/knowledge-base/rag-index
	GetOrCreateRagIndexes(ctx context.Context, req *BodyComputeRAGIndexesInBatchV1ConvaiKnowledgeBaseRagIndexPost, params GetOrCreateRagIndexesParams) (GetOrCreateRagIndexesRes, error)
	// GetPhoneNumberRoute implements get_phone_number_route operation.
	//
	// Retrieve Phone Number details by ID.
	//
	// GET /v1/convai/phone-numbers/{phone_number_id}
	GetPhoneNumberRoute(ctx context.Context, params GetPhoneNumberRouteParams) (GetPhoneNumberRouteRes, error)
	// GetProjectMutedTracksEndpoint implements get_project_muted_tracks_endpoint operation.
	//
	// Returns a list of chapter IDs that have muted tracks in a project.
	//
	// GET /v1/studio/projects/{project_id}/muted-tracks
	GetProjectMutedTracksEndpoint(ctx context.Context, params GetProjectMutedTracksEndpointParams) (GetProjectMutedTracksEndpointRes, error)
	// GetProjectSnapshotEndpoint implements get_project_snapshot_endpoint operation.
	//
	// Returns the project snapshot.
	//
	// GET /v1/studio/projects/{project_id}/snapshots/{project_snapshot_id}
	GetProjectSnapshotEndpoint(ctx context.Context, params GetProjectSnapshotEndpointParams) (GetProjectSnapshotEndpointRes, error)
	// GetProjectSnapshots implements get_project_snapshots operation.
	//
	// Retrieves a list of snapshots for a Studio project.
	//
	// GET /v1/studio/projects/{project_id}/snapshots
	GetProjectSnapshots(ctx context.Context, params GetProjectSnapshotsParams) (GetProjectSnapshotsRes, error)
	// GetProjects implements get_projects operation.
	//
	// Returns a list of your Studio projects with metadata.
	//
	// GET /v1/studio/projects
	GetProjects(ctx context.Context, params GetProjectsParams) (GetProjectsRes, error)
	// GetPronunciationDictionariesMetadata implements get_pronunciation_dictionaries_metadata operation.
	//
	// Get a list of the pronunciation dictionaries you have access to and their metadata.
	//
	// GET /v1/pronunciation-dictionaries
	GetPronunciationDictionariesMetadata(ctx context.Context, params GetPronunciationDictionariesMetadataParams) (GetPronunciationDictionariesMetadataRes, error)
	// GetPronunciationDictionaryVersionPls implements get_pronunciation_dictionary_version_pls operation.
	//
	// Get a PLS file with a pronunciation dictionary version rules.
	//
	// GET /v1/pronunciation-dictionaries/{dictionary_id}/{version_id}/download
	GetPronunciationDictionaryVersionPls(ctx context.Context, params GetPronunciationDictionaryVersionPlsParams) (GetPronunciationDictionaryVersionPlsRes, error)
	// GetPublicLlmExpectedCostCalculation implements get_public_llm_expected_cost_calculation operation.
	//
	// Returns a list of LLM models and the expected cost for using them based on the provided values.
	//
	// POST /v1/convai/llm-usage/calculate
	GetPublicLlmExpectedCostCalculation(ctx context.Context, req *LLMUsageCalculatorPublicRequestModel) (GetPublicLlmExpectedCostCalculationRes, error)
	// GetPvcSampleAudio implements get_pvc_sample_audio operation.
	//
	// Retrieve the first 30 seconds of voice sample audio with or without noise removal.
	//
	// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/audio
	GetPvcSampleAudio(ctx context.Context, params GetPvcSampleAudioParams) (GetPvcSampleAudioRes, error)
	// GetPvcSampleSpeakers implements get_pvc_sample_speakers operation.
	//
	// Retrieve the status of the speaker separation process and the list of detected speakers if
	// complete.
	//
	// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/speakers
	GetPvcSampleSpeakers(ctx context.Context, params GetPvcSampleSpeakersParams) (GetPvcSampleSpeakersRes, error)
	// GetPvcSampleVisualWaveform implements get_pvc_sample_visual_waveform operation.
	//
	// Retrieve the visual waveform of a voice sample.
	//
	// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/waveform
	GetPvcSampleVisualWaveform(ctx context.Context, params GetPvcSampleVisualWaveformParams) (GetPvcSampleVisualWaveformRes, error)
	// GetPvcVoiceCaptcha implements get_pvc_voice_captcha operation.
	//
	// Get captcha for PVC voice verification.
	//
	// GET /v1/voices/pvc/{voice_id}/captcha
	GetPvcVoiceCaptcha(ctx context.Context, params GetPvcVoiceCaptchaParams) (GetPvcVoiceCaptchaRes, error)
	// GetRagIndexOverview implements get_rag_index_overview operation.
	//
	// Provides total size and other information of RAG indexes used by knowledgebase documents.
	//
	// GET /v1/convai/knowledge-base/rag-index
	GetRagIndexOverview(ctx context.Context, params GetRagIndexOverviewParams) (GetRagIndexOverviewRes, error)
	// GetRagIndexes implements get_rag_indexes operation.
	//
	// Provides information about all RAG indexes of the specified knowledgebase document.
	//
	// GET /v1/convai/knowledge-base/{documentation_id}/rag-index
	GetRagIndexes(ctx context.Context, params GetRagIndexesParams) (GetRagIndexesRes, error)
	// GetResourceMetadata implements get_resource_metadata operation.
	//
	// Gets the metadata of a resource by ID.
	//
	// GET /v1/workspace/resources/{resource_id}
	GetResourceMetadata(ctx context.Context, params GetResourceMetadataParams) (GetResourceMetadataRes, error)
	// GetSecretRoute implements get_secret_route operation.
	//
	// Get a workspace secret by ID.
	//
	// GET /v1/convai/secrets/{secret_id}
	GetSecretRoute(ctx context.Context, params GetSecretRouteParams) (GetSecretRouteRes, error)
	// GetSecretsRoute implements get_secrets_route operation.
	//
	// Get all workspace secrets for the user.
	//
	// GET /v1/convai/secrets
	GetSecretsRoute(ctx context.Context, params GetSecretsRouteParams) (GetSecretsRouteRes, error)
	// GetServiceAccountAPIKeysRoute implements get_service_account_api_keys_route operation.
	//
	// Get all API keys for a service account.
	//
	// GET /v1/service-accounts/{service_account_user_id}/api-keys
	GetServiceAccountAPIKeysRoute(ctx context.Context, params GetServiceAccountAPIKeysRouteParams) (GetServiceAccountAPIKeysRouteRes, error)
	// GetSettingsRoute implements get_settings_route operation.
	//
	// Retrieve Convai settings for the workspace.
	//
	// GET /v1/convai/settings
	GetSettingsRoute(ctx context.Context, params GetSettingsRouteParams) (GetSettingsRouteRes, error)
	// GetSignedURLDeprecated implements get_signed_url_deprecated operation.
	//
	// Get a signed url to start a conversation with an agent with an agent that requires authorization.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/convai/conversation/get_signed_url
	GetSignedURLDeprecated(ctx context.Context, params GetSignedURLDeprecatedParams) (GetSignedURLDeprecatedRes, error)
	// GetSimilarLibraryVoices implements get_similar_library_voices operation.
	//
	// Returns a list of shared voices similar to the provided audio sample. If neither
	// similarity_threshold nor top_k is provided, we will apply default values.
	//
	// POST /v1/similar-voices
	GetSimilarLibraryVoices(ctx context.Context, req OptBodyGetSimilarLibraryVoicesV1SimilarVoicesPostMultipart, params GetSimilarLibraryVoicesParams) (GetSimilarLibraryVoicesRes, error)
	// GetSimilarVoicesForSpeaker implements get_similar_voices_for_speaker operation.
	//
	// Fetch the top 10 similar voices to a speaker, including the voice IDs, names, descriptions, and,
	// where possible, a sample audio recording.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}/similar-voices
	GetSimilarVoicesForSpeaker(ctx context.Context, params GetSimilarVoicesForSpeakerParams) (GetSimilarVoicesForSpeakerRes, error)
	// GetSingleUseToken implements get_single_use_token operation.
	//
	// Generate a time limited single-use token with embedded authentication for frontend clients.
	//
	// POST /v1/single-use-token/{token_type}
	GetSingleUseToken(ctx context.Context, params GetSingleUseTokenParams) (GetSingleUseTokenRes, error)
	// GetSpeakerAudio implements get_speaker_audio operation.
	//
	// Retrieve the separated audio for a specific speaker.
	//
	// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/speakers/{speaker_id}/audio
	GetSpeakerAudio(ctx context.Context, params GetSpeakerAudioParams) (GetSpeakerAudioRes, error)
	// GetSpeechHistory implements get_speech_history operation.
	//
	// Returns a list of your generated audio.
	//
	// GET /v1/history
	GetSpeechHistory(ctx context.Context, params GetSpeechHistoryParams) (GetSpeechHistoryRes, error)
	// GetSpeechHistoryItemByID implements get_speech_history_item_by_id operation.
	//
	// Retrieves a history item.
	//
	// GET /v1/history/{history_item_id}
	GetSpeechHistoryItemByID(ctx context.Context, params GetSpeechHistoryItemByIDParams) (GetSpeechHistoryItemByIDRes, error)
	// GetTestInvocationRoute implements get_test_invocation_route operation.
	//
	// Gets a test invocation by ID.
	//
	// GET /v1/convai/test-invocations/{test_invocation_id}
	GetTestInvocationRoute(ctx context.Context, params GetTestInvocationRouteParams) (GetTestInvocationRouteRes, error)
	// GetToolDependentAgentsRoute implements get_tool_dependent_agents_route operation.
	//
	// Get a list of agents depending on this tool.
	//
	// GET /v1/convai/tools/{tool_id}/dependent-agents
	GetToolDependentAgentsRoute(ctx context.Context, params GetToolDependentAgentsRouteParams) (GetToolDependentAgentsRouteRes, error)
	// GetToolExecutionsRoute implements get_tool_executions_route operation.
	//
	// Get paginated list of tool executions for a specific tool.
	//
	// GET /v1/convai/tools/{tool_id}/executions
	GetToolExecutionsRoute(ctx context.Context, params GetToolExecutionsRouteParams) (GetToolExecutionsRouteRes, error)
	// GetTranscriptByID implements get_transcript_by_id operation.
	//
	// Retrieve a previously generated transcript by its ID.
	//
	// GET /v1/speech-to-text/transcripts/{transcription_id}
	GetTranscriptByID(ctx context.Context, params GetTranscriptByIDParams) (GetTranscriptByIDRes, error)
	// GetUserInfo implements get_user_info operation.
	//
	// Gets information about the user.
	//
	// GET /v1/user
	GetUserInfo(ctx context.Context, params GetUserInfoParams) (GetUserInfoRes, error)
	// GetUserVoicesV2 implements get_user_voices_v2 operation.
	//
	// Gets a list of all available voices for a user with search, filtering and pagination.
	//
	// GET /v2/voices
	GetUserVoicesV2(ctx context.Context, params GetUserVoicesV2Params) (GetUserVoicesV2Res, error)
	// GetVersionMetadataRoute implements get_version_metadata_route operation.
	//
	// Get metadata for a specific agent version.
	//
	// GET /v1/convai/agents/{agent_id}/versions/{version_id}
	GetVersionMetadataRoute(ctx context.Context, params GetVersionMetadataRouteParams) (GetVersionMetadataRouteRes, error)
	// GetVoiceByID implements get_voice_by_id operation.
	//
	// Returns metadata about a specific voice.
	//
	// GET /v1/voices/{voice_id}
	GetVoiceByID(ctx context.Context, params GetVoiceByIDParams) (GetVoiceByIDRes, error)
	// GetVoiceSettings implements get_voice_settings operation.
	//
	// Returns the settings for a specific voice. "similarity_boost" corresponds to"Clarity + Similarity
	// Enhancement" in the web app and "stability" corresponds to "Stability" slider in the web app.
	//
	// GET /v1/voices/{voice_id}/settings
	GetVoiceSettings(ctx context.Context, params GetVoiceSettingsParams) (GetVoiceSettingsRes, error)
	// GetVoiceSettingsDefault implements get_voice_settings_default operation.
	//
	// Gets the default settings for voices. "similarity_boost" corresponds to"Clarity + Similarity
	// Enhancement" in the web app and "stability" corresponds to "Stability" slider in the web app.
	//
	// GET /v1/voices/settings/default
	GetVoiceSettingsDefault(ctx context.Context) (*VoiceSettingsResponseModel, error)
	// GetVoices implements get_voices operation.
	//
	// Returns a list of all available voices for a user. Stops working once the user's workspace exceeds
	// 500 voices.
	//
	// GET /v1/voices
	GetVoices(ctx context.Context, params GetVoicesParams) (GetVoicesRes, error)
	// GetWhatsappAccount implements get_whatsapp_account operation.
	//
	// Get a WhatsApp account.
	//
	// GET /v1/convai/whatsapp-accounts/{phone_number_id}
	GetWhatsappAccount(ctx context.Context, params GetWhatsappAccountParams) (GetWhatsappAccountRes, error)
	// GetWorkspaceBatchCalls implements get_workspace_batch_calls operation.
	//
	// Get all batch calls for the current workspace.
	//
	// GET /v1/convai/batch-calling/workspace
	GetWorkspaceBatchCalls(ctx context.Context, params GetWorkspaceBatchCallsParams) (GetWorkspaceBatchCallsRes, error)
	// GetWorkspaceServiceAccounts implements get_workspace_service_accounts operation.
	//
	// List all service accounts in the workspace.
	//
	// GET /v1/service-accounts
	GetWorkspaceServiceAccounts(ctx context.Context, params GetWorkspaceServiceAccountsParams) (GetWorkspaceServiceAccountsRes, error)
	// GetWorkspaceWebhooksRoute implements get_workspace_webhooks_route operation.
	//
	// List all webhooks for a workspace.
	//
	// GET /v1/workspace/webhooks
	GetWorkspaceWebhooksRoute(ctx context.Context, params GetWorkspaceWebhooksRouteParams) (GetWorkspaceWebhooksRouteRes, error)
	// HandleExotelOutboundCall implements handle_exotel_outbound_call operation.
	//
	// Handle an outbound call via Exotel Connect API.
	//
	// POST /v1/convai/exotel/outbound-call
	HandleExotelOutboundCall(ctx context.Context, req *BodyHandleAnOutboundCallViaExotelV1ConvaiExotelOutboundCallPost, params HandleExotelOutboundCallParams) (HandleExotelOutboundCallRes, error)
	// HandleSipTrunkOutboundCall implements handle_sip_trunk_outbound_call operation.
	//
	// Handle an outbound call via SIP trunk.
	//
	// POST /v1/convai/sip-trunk/outbound-call
	HandleSipTrunkOutboundCall(ctx context.Context, req *BodyHandleAnOutboundCallViaSIPTrunkV1ConvaiSipTrunkOutboundCallPost, params HandleSipTrunkOutboundCallParams) (HandleSipTrunkOutboundCallRes, error)
	// HandleTwilioOutboundCall implements handle_twilio_outbound_call operation.
	//
	// Handle an outbound call via Twilio.
	//
	// POST /v1/convai/twilio/outbound-call
	HandleTwilioOutboundCall(ctx context.Context, req *BodyHandleAnOutboundCallViaTwilioV1ConvaiTwilioOutboundCallPost, params HandleTwilioOutboundCallParams) (HandleTwilioOutboundCallRes, error)
	// InviteUser implements invite_user operation.
	//
	// Sends an email invitation to join your workspace to the provided email. If the user doesn't have
	// an account they will be prompted to create one. If the user accepts this invite they will be added
	// as a user to your workspace and your subscription using one of your seats. This endpoint may only
	// be called by workspace members with the WORKSPACE_MEMBERS_INVITE permission. If the user is
	// already in the workspace a 400 error will be returned.
	//
	// POST /v1/workspace/invites/add
	InviteUser(ctx context.Context, req *BodyInviteUserV1WorkspaceInvitesAddPost, params InviteUserParams) (InviteUserRes, error)
	// InviteUsersBulk implements invite_users_bulk operation.
	//
	// Sends email invitations to join your workspace to the provided emails. Requires all email
	// addresses to be part of a verified domain. If the users don't have an account they will be
	// prompted to create one. If the users accept these invites they will be added as users to your
	// workspace and your subscription using one of your seats. This endpoint may only be called by
	// workspace members with the WORKSPACE_MEMBERS_INVITE permission.
	//
	// POST /v1/workspace/invites/add-bulk
	InviteUsersBulk(ctx context.Context, req *BodyInviteMultipleUsersV1WorkspaceInvitesAddBulkPost, params InviteUsersBulkParams) (InviteUsersBulkRes, error)
	// ListAuthConnections implements list_auth_connections operation.
	//
	// Get all auth connections for the workspace.
	//
	// GET /v1/workspace/auth-connections
	ListAuthConnections(ctx context.Context, params ListAuthConnectionsParams) (ListAuthConnectionsRes, error)
	// ListAvailableLlms implements list_available_llms operation.
	//
	// Returns a list of available LLM models that can be used with agents, including their capabilities
	// and any deprecation status. The response is filtered based on the data residency of the deployment
	// and any compliance requirements (e.g. HIPAA) of the workspace subscription.
	//
	// GET /v1/convai/llm/list
	ListAvailableLlms(ctx context.Context, params ListAvailableLlmsParams) (ListAvailableLlmsRes, error)
	// ListChatResponseTestsRoute implements list_chat_response_tests_route operation.
	//
	// Lists all agent response tests with pagination support and optional search filtering.
	//
	// GET /v1/convai/agent-testing
	ListChatResponseTestsRoute(ctx context.Context, params ListChatResponseTestsRouteParams) (ListChatResponseTestsRouteRes, error)
	// ListConversationTagsRoute implements list_conversation_tags_route operation.
	//
	// List conversation tags for the workspace, ordered by most recently created first.
	//
	// GET /v1/convai/tags
	ListConversationTagsRoute(ctx context.Context, params ListConversationTagsRouteParams) (ListConversationTagsRouteRes, error)
	// ListDubs implements list_dubs operation.
	//
	// List the dubs you have access to.
	//
	// GET /v1/dubbing
	ListDubs(ctx context.Context, params ListDubsParams) (ListDubsRes, error)
	// ListMcpServerToolsRoute implements list_mcp_server_tools_route operation.
	//
	// Retrieve all tools available for a specific MCP server configuration.
	//
	// GET /v1/convai/mcp-servers/{mcp_server_id}/tools
	ListMcpServerToolsRoute(ctx context.Context, params ListMcpServerToolsRouteParams) (ListMcpServerToolsRouteRes, error)
	// ListPhoneNumbersRoute implements list_phone_numbers_route operation.
	//
	// Retrieve all Phone Numbers.
	//
	// GET /v1/convai/phone-numbers
	ListPhoneNumbersRoute(ctx context.Context, params ListPhoneNumbersRouteParams) (ListPhoneNumbersRouteRes, error)
	// ListSipMessages implements list_sip_messages operation.
	//
	// Get SIP messages for a phone number.
	//
	// GET /v1/convai/phone-numbers/{phone_number_id}/sip-messages
	ListSipMessages(ctx context.Context, params ListSipMessagesParams) (ListSipMessagesRes, error)
	// ListSpeechEngines implements list_speech_engines operation.
	//
	// Returns a paginated list of Speech Engine resources.
	//
	// GET /v1/speech-engine
	ListSpeechEngines(ctx context.Context, params ListSpeechEnginesParams) (ListSpeechEnginesRes, error)
	// ListTestInvocationsRoute implements list_test_invocations_route operation.
	//
	// Lists all test invocations with pagination support and optional search filtering.
	//
	// GET /v1/convai/test-invocations
	ListTestInvocationsRoute(ctx context.Context, params ListTestInvocationsRouteParams) (ListTestInvocationsRouteRes, error)
	// ListWhatsappAccounts implements list_whatsapp_accounts operation.
	//
	// List all WhatsApp accounts.
	//
	// GET /v1/convai/whatsapp-accounts
	ListWhatsappAccounts(ctx context.Context, params ListWhatsappAccountsParams) (ListWhatsappAccountsRes, error)
	// MergeBranchIntoTarget implements merge_branch_into_target operation.
	//
	// Merge a branch into a target branch.
	//
	// POST /v1/convai/agents/{agent_id}/branches/{source_branch_id}/merge
	MergeBranchIntoTarget(ctx context.Context, req OptBodyMergeABranchIntoATargetBranchV1ConvaiAgentsAgentIDBranchesSourceBranchIDMergePost, params MergeBranchIntoTargetParams) (MergeBranchIntoTargetRes, error)
	// MigrateSegments implements migrate_segments operation.
	//
	// Change the attribution of one or more segments to a different speaker.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/migrate-segments
	MigrateSegments(ctx context.Context, req *BodyMoveSegmentsBetweenSpeakersV1DubbingResourceDubbingIDMigrateSegmentsPost, params MigrateSegmentsParams) (MigrateSegmentsRes, error)
	// PatchPronunciationDictionary implements patch_pronunciation_dictionary operation.
	//
	// Partially update the pronunciation dictionary without changing the version.
	//
	// PATCH /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}
	PatchPronunciationDictionary(ctx context.Context, req OptBodyUpdatePronunciationDictionaryV1PronunciationDictionariesPronunciationDictionaryIDPatch, params PatchPronunciationDictionaryParams) (PatchPronunciationDictionaryRes, error)
	// PostAgentAvatarRoute implements post_agent_avatar_route operation.
	//
	// Sets the avatar for an agent displayed in the widget.
	//
	// POST /v1/convai/agents/{agent_id}/avatar
	PostAgentAvatarRoute(ctx context.Context, req *BodyPostAgentAvatarV1ConvaiAgentsAgentIDAvatarPostMultipart, params PostAgentAvatarRouteParams) (PostAgentAvatarRouteRes, error)
	// PostConversationFeedbackRoute implements post_conversation_feedback_route operation.
	//
	// Send the feedback for the given conversation.
	//
	// POST /v1/convai/conversations/{conversation_id}/feedback
	PostConversationFeedbackRoute(ctx context.Context, req *ConversationFeedbackRequestModel, params PostConversationFeedbackRouteParams) (PostConversationFeedbackRouteRes, error)
	// PostKnowledgeBaseBulkMoveRoute implements post_knowledge_base_bulk_move_route operation.
	//
	// Moves multiple entities from one folder to another.
	//
	// POST /v1/convai/knowledge-base/bulk-move
	PostKnowledgeBaseBulkMoveRoute(ctx context.Context, req *BodyBulkMoveEntitiesToFolderV1ConvaiKnowledgeBaseBulkMovePost, params PostKnowledgeBaseBulkMoveRouteParams) (PostKnowledgeBaseBulkMoveRouteRes, error)
	// PostKnowledgeBaseMoveRoute implements post_knowledge_base_move_route operation.
	//
	// Moves the entity from one folder to another.
	//
	// POST /v1/convai/knowledge-base/{document_id}/move
	PostKnowledgeBaseMoveRoute(ctx context.Context, req OptBodyMoveEntityToFolderV1ConvaiKnowledgeBaseDocumentIDMovePost, params PostKnowledgeBaseMoveRouteParams) (PostKnowledgeBaseMoveRouteRes, error)
	// PublicCreateOrder implements public_create_order operation.
	//
	// Creates a new Productions order in the workspace. The order starts in the open state and can be
	// configured with items before submission.
	//
	// POST /v1/productions/orders
	PublicCreateOrder(ctx context.Context, req OptCreateOrderRequest, params PublicCreateOrderParams) (PublicCreateOrderRes, error)
	// PublicGetAvailableLanguages implements public_get_available_languages operation.
	//
	// Returns the available languages for a given order item kind.
	//
	// GET /v1/productions/orders/languages/{order_item_kind}
	PublicGetAvailableLanguages(ctx context.Context, params PublicGetAvailableLanguagesParams) (PublicGetAvailableLanguagesRes, error)
	// PublicGetMediaInfo implements public_get_media_info operation.
	//
	// Retrieves metadata and a time-limited download URL for a previously uploaded media file.
	//
	// GET /v1/productions/orders/{order_id}/media/{media_id}
	PublicGetMediaInfo(ctx context.Context, params PublicGetMediaInfoParams) (PublicGetMediaInfoRes, error)
	// PublicGetOrder implements public_get_order operation.
	//
	// Retrieves full details for a Productions order.
	// Quote and pricing information may not be available immediately; if you wish to see the quote
	// before submission, you may need to poll the order details until it is ready.
	//
	// GET /v1/productions/orders/{order_id}
	PublicGetOrder(ctx context.Context, params PublicGetOrderParams) (PublicGetOrderRes, error)
	// PublicGetOrderDeliverables implements public_get_order_deliverables operation.
	//
	// Retrieves the delivered files for a completed order. Returns an empty list if the order is not yet
	// completed.
	//
	// GET /v1/productions/orders/{order_id}/deliverables
	PublicGetOrderDeliverables(ctx context.Context, params PublicGetOrderDeliverablesParams) (PublicGetOrderDeliverablesRes, error)
	// PublicListOrders implements public_list_orders operation.
	//
	// Lists Productions orders in the workspace. Supports filtering by status and date range, with
	// pagination.
	//
	// GET /v1/productions/orders
	PublicListOrders(ctx context.Context, params PublicListOrdersParams) (PublicListOrdersRes, error)
	// PublicRegisterMedia implements public_register_media operation.
	//
	// Registers a media file with an order, either by uploading it directly or by providing a URL to
	// fetch it from. Exactly one of `media` or `media_url` must be provided. The registered media can
	// then be referenced when adding order items.
	//
	// POST /v1/productions/orders/{order_id}/media
	PublicRegisterMedia(ctx context.Context, req *BodyRegisterMediaV1ProductionsOrdersOrderIDMediaPostMultipart, params PublicRegisterMediaParams) (PublicRegisterMediaRes, error)
	// PublicRemoveOrderItem implements public_remove_order_item operation.
	//
	// Removes an order item from an open order.
	//
	// DELETE /v1/productions/orders/{order_id}/items/{item_id}
	PublicRemoveOrderItem(ctx context.Context, params PublicRemoveOrderItemParams) (PublicRemoveOrderItemRes, error)
	// PublicSubmitOrder implements public_submit_order operation.
	//
	// Submits an open order for processing. The order must have at least one item. Once submitted, items
	// can no longer be modified.
	// Upon submission, the workspace will be charged for the order. The quote is based on information
	// extracted from the uploaded media, such as its duration. The quote may not be available
	// immediately; if you wish to see the quote before submission, you may need to poll the order
	// details until the quote is ready.
	//
	// POST /v1/productions/orders/{order_id}/submit
	PublicSubmitOrder(ctx context.Context, params PublicSubmitOrderParams) (PublicSubmitOrderRes, error)
	// PublicUpdateOrder implements public_update_order operation.
	//
	// Updates an open order.
	//
	// PATCH /v1/productions/orders/{order_id}
	PublicUpdateOrder(ctx context.Context, req *BodyUpdateOrderV1ProductionsOrdersOrderIDPatch, params PublicUpdateOrderParams) (PublicUpdateOrderRes, error)
	// PublicUpsertOrderItem implements public_upsert_order_item operation.
	//
	// Adds or updates an order item on an open order. Returns the item ID and the quoted price.
	//
	// POST /v1/productions/orders/{order_id}/items
	PublicUpsertOrderItem(ctx context.Context, req *BodyUpsertOrderItemV1ProductionsOrdersOrderIDItemsPost, params PublicUpsertOrderItemParams) (PublicUpsertOrderItemRes, error)
	// RagIndexStatus implements rag_index_status operation.
	//
	// In case the document is not RAG indexed, it triggers rag indexing task, otherwise it just returns
	// the current status.
	//
	// POST /v1/convai/knowledge-base/{documentation_id}/rag-index
	RagIndexStatus(ctx context.Context, req *RAGIndexRequestModel, params RagIndexStatusParams) (RagIndexStatusRes, error)
	// RedirectToMintlify implements redirect_to_mintlify operation.
	//
	// Redirect To Mintlify.
	//
	// GET /docs
	RedirectToMintlify(ctx context.Context) (jx.Raw, error)
	// RefreshURLDocumentRoute implements refresh_url_document_route operation.
	//
	// Manually refresh a URL document by re-fetching its content from the source URL.
	//
	// POST /v1/convai/knowledge-base/{documentation_id}/refresh
	RefreshURLDocumentRoute(ctx context.Context, params RefreshURLDocumentRouteParams) (RefreshURLDocumentRouteRes, error)
	// RegisterTwilioCall implements register_twilio_call operation.
	//
	// Register a Twilio call and return TwiML to connect the call.
	//
	// POST /v1/convai/twilio/register-call
	RegisterTwilioCall(ctx context.Context, req *BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPost, params RegisterTwilioCallParams) (RegisterTwilioCallRes, error)
	// RemoveMember implements remove_member operation.
	//
	// Removes a member from the specified group. Requires `group_members_manage` permission.
	//
	// POST /v1/workspace/groups/{group_id}/members/remove
	RemoveMember(ctx context.Context, req *BodyDeleteMemberFromUserGroupV1WorkspaceGroupsGroupIDMembersRemovePost, params RemoveMemberParams) (RemoveMemberRes, error)
	// RemoveRules implements remove_rules operation.
	//
	// Remove rules from the pronunciation dictionary.
	//
	// POST /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}/remove-rules
	RemoveRules(ctx context.Context, req *BodyRemoveRulesFromThePronunciationDictionaryV1PronunciationDictionariesPronunciationDictionaryIDRemoveRulesPost, params RemoveRulesParams) (RemoveRulesRes, error)
	// Render implements render operation.
	//
	// Regenerate the output media for a language using the latest Studio state. Please ensure all
	// segments have been dubbed before rendering, otherwise they will be omitted. Renders are generated
	// asynchronously, and to check the status of all renders please use the 'Get Dubbing Resource'
	// endpoint.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/render/{language}
	Render(ctx context.Context, req *BodyRenderAudioOrVideoForTheGivenLanguageV1DubbingResourceDubbingIDRenderLanguagePost, params RenderParams) (RenderRes, error)
	// RequestPvcManualVerification implements request_pvc_manual_verification operation.
	//
	// Request manual verification for a PVC voice.
	//
	// POST /v1/voices/pvc/{voice_id}/verification
	RequestPvcManualVerification(ctx context.Context, req *BodyRequestManualVerificationV1VoicesPvcVoiceIDVerificationPostMultipart, params RequestPvcManualVerificationParams) (RequestPvcManualVerificationRes, error)
	// RetryBatchCall implements retry_batch_call operation.
	//
	// Retry a batch call, calling failed and no-response recipients again.
	//
	// POST /v1/convai/batch-calling/{batch_id}/retry
	RetryBatchCall(ctx context.Context, params RetryBatchCallParams) (RetryBatchCallRes, error)
	// RunConversationAnalysis implements run_conversation_analysis operation.
	//
	// Run the analysis for a conversation using the agent's current evaluation criteria and data
	// collection settings.
	//
	// POST /v1/convai/conversations/{conversation_id}/analysis/run
	RunConversationAnalysis(ctx context.Context, params RunConversationAnalysisParams) (RunConversationAnalysisRes, error)
	// RunConversationEvaluations implements run_conversation_evaluations operation.
	//
	// Rerun a specific evaluation for a conversation.
	//
	// POST /v1/convai/conversations/{conversation_id}/analysis/evaluations/run
	RunConversationEvaluations(ctx context.Context, req *RunConversationEvaluationsRequest, params RunConversationEvaluationsParams) (RunConversationEvaluationsRes, error)
	// RunPvcVoiceTraining implements run_pvc_voice_training operation.
	//
	// Start PVC training process for a voice.
	//
	// POST /v1/voices/pvc/{voice_id}/train
	RunPvcVoiceTraining(ctx context.Context, req OptBodyRunPVCTrainingV1VoicesPvcVoiceIDTrainPost, params RunPvcVoiceTrainingParams) (RunPvcVoiceTrainingRes, error)
	// SearchGroups implements search_groups operation.
	//
	// Searches for user groups in the workspace. Multiple or no groups may be returned.
	//
	// GET /v1/workspace/groups/search
	SearchGroups(ctx context.Context, params SearchGroupsParams) (SearchGroupsRes, error)
	// SearchKnowledgeBaseContentRoute implements search_knowledge_base_content_route operation.
	//
	// Fuzzy text search over knowledge base document content.
	//
	// GET /v1/convai/knowledge-base/search
	SearchKnowledgeBaseContentRoute(ctx context.Context, params SearchKnowledgeBaseContentRouteParams) (SearchKnowledgeBaseContentRouteRes, error)
	// SeparateSongStems implements separate_song_stems operation.
	//
	// Separate an audio file into individual stems. This endpoint might have high latency, depending on
	// the length of the audio file.
	//
	// POST /v1/music/stem-separation
	SeparateSongStems(ctx context.Context, req *BodyStemSeparationV1MusicStemSeparationPostMultipart, params SeparateSongStemsParams) (SeparateSongStemsRes, error)
	// ShareResourceEndpoint implements share_resource_endpoint operation.
	//
	// Grants a role (one of 'admin', 'editor', 'commenter', or 'viewer') on a workspace resource to a
	// user, group, or workspace (service account) API key. This overrides any existing role the target
	// has on the resource. To target a user or service account, pass only the user email; the user must
	// be in your workspace. To target a group, pass only the group id. To target a workspace (service
	// account) API key, pass the api key id; the resource will be shared with the service account
	// associated with that key. You must have admin access to the resource to share it.
	//
	// POST /v1/workspace/resources/{resource_id}/share
	ShareResourceEndpoint(ctx context.Context, req *BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIDSharePost, params ShareResourceEndpointParams) (ShareResourceEndpointRes, error)
	// SmartSearchConversationMessagesRoute implements smart_search_conversation_messages_route operation.
	//
	// Search conversation transcripts by semantic similarity to surface relevant messages based on
	// meaning and intent, rather than exact keyword matches.
	//
	// GET /v1/convai/conversations/messages/smart-search
	SmartSearchConversationMessagesRoute(ctx context.Context, params SmartSearchConversationMessagesRouteParams) (SmartSearchConversationMessagesRouteRes, error)
	// SoundGeneration implements sound_generation operation.
	//
	// Turn text into sound effects for your videos, voice-overs or video games using the most advanced
	// sound effects models in the world.
	//
	// POST /v1/sound-generation
	SoundGeneration(ctx context.Context, req *BodySoundGenerationV1SoundGenerationPost, params SoundGenerationParams) (SoundGenerationRes, error)
	// SpeechToSpeechFull implements speech_to_speech_full operation.
	//
	// Transform audio from one voice to another. Maintain full control over emotion, timing and delivery.
	//
	// POST /v1/speech-to-speech/{voice_id}
	SpeechToSpeechFull(ctx context.Context, req *BodySpeechToSpeechV1SpeechToSpeechVoiceIDPostMultipart, params SpeechToSpeechFullParams) (SpeechToSpeechFullRes, error)
	// SpeechToSpeechStream implements speech_to_speech_stream operation.
	//
	// Stream audio from one voice to another. Maintain full control over emotion, timing and delivery.
	//
	// POST /v1/speech-to-speech/{voice_id}/stream
	SpeechToSpeechStream(ctx context.Context, req *BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIDStreamPostMultipart, params SpeechToSpeechStreamParams) (SpeechToSpeechStreamRes, error)
	// SpeechToText implements speech_to_text operation.
	//
	// Transcribe an audio or video file. If webhook is set to true, the request will be processed
	// asynchronously and results sent to configured webhooks. When use_multi_channel is true and the
	// provided audio has multiple channels, a 'transcripts' object with separate transcripts for each
	// channel is returned. Otherwise, returns a single transcript. The optional webhook_metadata
	// parameter allows you to attach custom data that will be included in webhook responses for request
	// correlation and tracking.
	//
	// POST /v1/speech-to-text
	SpeechToText(ctx context.Context, req *BodySpeechToTextV1SpeechToTextPostMultipart, params SpeechToTextParams) (SpeechToTextRes, error)
	// StartSpeakerSeparation implements start_speaker_separation operation.
	//
	// Start speaker separation process for a sample.
	//
	// POST /v1/voices/pvc/{voice_id}/samples/{sample_id}/separate-speakers
	StartSpeakerSeparation(ctx context.Context, params StartSpeakerSeparationParams) (StartSpeakerSeparationRes, error)
	// StreamChapterSnapshotAudio implements stream_chapter_snapshot_audio operation.
	//
	// Stream the audio from a chapter snapshot. Use `GET
	// /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots` to return the snapshots of a
	// chapter.
	//
	// POST /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots/{chapter_snapshot_id}/stream
	StreamChapterSnapshotAudio(ctx context.Context, req OptBodyStreamChapterAudioV1StudioProjectsProjectIDChaptersChapterIDSnapshotsChapterSnapshotIDStreamPost, params StreamChapterSnapshotAudioParams) (StreamChapterSnapshotAudioRes, error)
	// StreamProjectSnapshotArchiveEndpoint implements stream_project_snapshot_archive_endpoint operation.
	//
	// Returns a compressed archive of the Studio project's audio.
	//
	// POST /v1/studio/projects/{project_id}/snapshots/{project_snapshot_id}/archive
	StreamProjectSnapshotArchiveEndpoint(ctx context.Context, params StreamProjectSnapshotArchiveEndpointParams) (StreamProjectSnapshotArchiveEndpointRes, error)
	// StreamProjectSnapshotAudioEndpoint implements stream_project_snapshot_audio_endpoint operation.
	//
	// Stream the audio from a Studio project snapshot.
	//
	// POST /v1/studio/projects/{project_id}/snapshots/{project_snapshot_id}/stream
	StreamProjectSnapshotAudioEndpoint(ctx context.Context, req OptBodyStreamStudioProjectAudioV1StudioProjectsProjectIDSnapshotsProjectSnapshotIDStreamPost, params StreamProjectSnapshotAudioEndpointParams) (StreamProjectSnapshotAudioEndpointRes, error)
	// TextSearchConversationMessagesRoute implements text_search_conversation_messages_route operation.
	//
	// Search through conversation transcript messages by full-text and fuzzy search.
	//
	// GET /v1/convai/conversations/messages/text-search
	TextSearchConversationMessagesRoute(ctx context.Context, params TextSearchConversationMessagesRouteParams) (TextSearchConversationMessagesRouteRes, error)
	// TextToDialogue implements text_to_dialogue operation.
	//
	// Converts a list of text and voice ID pairs into speech (dialogue) and returns audio.
	//
	// POST /v1/text-to-dialogue
	TextToDialogue(ctx context.Context, req *BodyTextToDialogueMultiVoiceV1TextToDialoguePost, params TextToDialogueParams) (TextToDialogueRes, error)
	// TextToDialogueFullWithTimestamps implements text_to_dialogue_full_with_timestamps operation.
	//
	// Generate dialogue from text with precise character-level timing information for audio-text
	// synchronization.
	//
	// POST /v1/text-to-dialogue/with-timestamps
	TextToDialogueFullWithTimestamps(ctx context.Context, req *BodyTextToDialogueFullWithTimestamps, params TextToDialogueFullWithTimestampsParams) (TextToDialogueFullWithTimestampsRes, error)
	// TextToDialogueStream implements text_to_dialogue_stream operation.
	//
	// Converts a list of text and voice ID pairs into speech (dialogue) and returns an audio stream.
	//
	// POST /v1/text-to-dialogue/stream
	TextToDialogueStream(ctx context.Context, req *BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPost, params TextToDialogueStreamParams) (TextToDialogueStreamRes, error)
	// TextToDialogueStreamWithTimestamps implements text_to_dialogue_stream_with_timestamps operation.
	//
	// Converts a list of text and voice ID pairs into speech (dialogue) and returns a stream of JSON
	// blobs containing audio as a base64 encoded string and timestamps.
	//
	// POST /v1/text-to-dialogue/stream/with-timestamps
	TextToDialogueStreamWithTimestamps(ctx context.Context, req *BodyTextToDialogueStreamWithTimestamps, params TextToDialogueStreamWithTimestampsParams) (TextToDialogueStreamWithTimestampsRes, error)
	// TextToSpeechFull implements text_to_speech_full operation.
	//
	// Converts text into speech using a voice of your choice and returns audio.
	//
	// POST /v1/text-to-speech/{voice_id}
	TextToSpeechFull(ctx context.Context, req *BodyTextToSpeechFull, params TextToSpeechFullParams) (TextToSpeechFullRes, error)
	// TextToSpeechFullWithTimestamps implements text_to_speech_full_with_timestamps operation.
	//
	// Generate speech from text with precise character-level timing information for audio-text
	// synchronization.
	//
	// POST /v1/text-to-speech/{voice_id}/with-timestamps
	TextToSpeechFullWithTimestamps(ctx context.Context, req *BodyTextToSpeechFullWithTimestamps, params TextToSpeechFullWithTimestampsParams) (TextToSpeechFullWithTimestampsRes, error)
	// TextToSpeechStream implements text_to_speech_stream operation.
	//
	// Converts text into speech using a voice of your choice and returns audio as an audio stream.
	//
	// POST /v1/text-to-speech/{voice_id}/stream
	TextToSpeechStream(ctx context.Context, req *BodyTextToSpeechStream, params TextToSpeechStreamParams) (TextToSpeechStreamRes, error)
	// TextToSpeechStreamWithTimestamps implements text_to_speech_stream_with_timestamps operation.
	//
	// Converts text into speech using a voice of your choice and returns a stream of JSONs containing
	// audio as a base64 encoded string together with information on when which character was spoken.
	//
	// POST /v1/text-to-speech/{voice_id}/stream/with-timestamps
	TextToSpeechStreamWithTimestamps(ctx context.Context, req *BodyTextToSpeechStreamWithTimestamps, params TextToSpeechStreamWithTimestampsParams) (TextToSpeechStreamWithTimestampsRes, error)
	// TextToVoice implements text_to_voice operation.
	//
	// **Deprecated.** Use `POST /v1/text-to-voice/design` instead. Generate a custom voice based on
	// voice description. This method returns a list of voice previews. Each preview has a
	// generated_voice_id and a sample of the voice as base64 encoded mp3 audio. To create the voice use
	// `POST /v1/text-to-voice` with the chosen `generated_voice_id`.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/text-to-voice/create-previews
	TextToVoice(ctx context.Context, req *VoicePreviewsRequestModel, params TextToVoiceParams) (TextToVoiceRes, error)
	// TextToVoiceDesign implements text_to_voice_design operation.
	//
	// Design a voice via a prompt. This method returns a list of voice previews. Each preview has a
	// generated_voice_id and a sample of the voice as base64 encoded mp3 audio. To create a voice use
	// the generated_voice_id of the preferred preview with the /v1/text-to-voice endpoint.
	//
	// POST /v1/text-to-voice/design
	TextToVoiceDesign(ctx context.Context, req *VoiceDesignRequestModel, params TextToVoiceDesignParams) (TextToVoiceDesignRes, error)
	// TextToVoicePreviewStream implements text_to_voice_preview_stream operation.
	//
	// Stream a voice preview that was created via the /v1/text-to-voice/design endpoint.
	//
	// GET /v1/text-to-voice/{generated_voice_id}/stream
	TextToVoicePreviewStream(ctx context.Context, params TextToVoicePreviewStreamParams) (TextToVoicePreviewStreamRes, error)
	// TextToVoiceRemix implements text_to_voice_remix operation.
	//
	// Remix an existing voice via a prompt. This method returns a list of voice previews. Each preview
	// has a generated_voice_id and a sample of the voice as base64 encoded mp3 audio. To create a voice
	// use the generated_voice_id of the preferred preview with the /v1/text-to-voice endpoint.
	//
	// POST /v1/text-to-voice/{voice_id}/remix
	TextToVoiceRemix(ctx context.Context, req *VoiceRemixRequestModel, params TextToVoiceRemixParams) (TextToVoiceRemixRes, error)
	// Transcribe implements transcribe operation.
	//
	// Regenerate the transcriptions for the specified segments. Does not automatically regenerate
	// translations or dubs.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/transcribe
	Transcribe(ctx context.Context, req *BodyTranscribesSegmentsV1DubbingResourceDubbingIDTranscribePost, params TranscribeParams) (TranscribeRes, error)
	// Translate implements translate operation.
	//
	// Regenerate the translations for either the entire resource or the specified segments/languages.
	// Will automatically transcribe missing transcriptions. Will not automatically regenerate the dubs.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/dubbing/resource/{dubbing_id}/translate
	Translate(ctx context.Context, req *BodyTranslatesAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDTranslatePost, params TranslateParams) (TranslateRes, error)
	// UnassignConversationTagRoute implements unassign_conversation_tag_route operation.
	//
	// Remove a single conversation tag from a conversation.
	//
	// DELETE /v1/convai/conversations/{conversation_id}/tags/{tag_id}
	UnassignConversationTagRoute(ctx context.Context, params UnassignConversationTagRouteParams) (UnassignConversationTagRouteRes, error)
	// UnshareResourceEndpoint implements unshare_resource_endpoint operation.
	//
	// Removes any existing role on a workspace resource from a user, group, or workspace (service
	// account) API key. To target a user or service account, pass only the user email; the user must be
	// in your workspace. To target a group, pass only the group id. To target a workspace (service
	// account) API key, pass the api key id; the resource will be unshared from the service account
	// associated with that key. You must have admin access to the resource to unshare it. You cannot
	// remove permissions from the user who created the resource.
	//
	// POST /v1/workspace/resources/{resource_id}/unshare
	UnshareResourceEndpoint(ctx context.Context, req *BodyUnshareWorkspaceResourceV1WorkspaceResourcesResourceIDUnsharePost, params UnshareResourceEndpointParams) (UnshareResourceEndpointRes, error)
	// UpdateAgentTestFolderRoute implements update_agent_test_folder_route operation.
	//
	// Updates an agent test folder. Currently only supports updating the folder name.
	//
	// PATCH /v1/convai/agent-testing/folders/{folder_id}
	UpdateAgentTestFolderRoute(ctx context.Context, req *BodyUpdateAgentTestFolderV1ConvaiAgentTestingFoldersFolderIDPatch, params UpdateAgentTestFolderRouteParams) (UpdateAgentTestFolderRouteRes, error)
	// UpdateBranchRoute implements update_branch_route operation.
	//
	// Update agent branch properties such as archiving status and protection level.
	//
	// PATCH /v1/convai/agents/{agent_id}/branches/{branch_id}
	UpdateBranchRoute(ctx context.Context, req OptBodyUpdateAgentBranchV1ConvaiAgentsAgentIDBranchesBranchIDPatch, params UpdateBranchRouteParams) (UpdateBranchRouteRes, error)
	// UpdateConversationTagRoute implements update_conversation_tag_route operation.
	//
	// Update a conversation tag's title and/or description. Restricted to the tag owner or a workspace
	// admin.
	//
	// PATCH /v1/convai/tags/{tag_id}
	UpdateConversationTagRoute(ctx context.Context, req *PatchConversationTagRequestModel, params UpdateConversationTagRouteParams) (UpdateConversationTagRouteRes, error)
	// UpdateDashboardSettingsRoute implements update_dashboard_settings_route operation.
	//
	// Update Convai dashboard settings for the workspace.
	//
	// PATCH /v1/convai/settings/dashboard
	UpdateDashboardSettingsRoute(ctx context.Context, req *PatchConvAIDashboardSettingsRequest, params UpdateDashboardSettingsRouteParams) (UpdateDashboardSettingsRouteRes, error)
	// UpdateDocumentRoute implements update_document_route operation.
	//
	// Update the name and/or content of a document.
	//
	// PATCH /v1/convai/knowledge-base/{documentation_id}
	UpdateDocumentRoute(ctx context.Context, req OptBodyUpdateDocumentV1ConvaiKnowledgeBaseDocumentationIDPatch, params UpdateDocumentRouteParams) (UpdateDocumentRouteRes, error)
	// UpdateFileDocumentRoute implements update_file_document_route operation.
	//
	// Update the source file of a file document. The document name, content, and metadata are updated to
	// reflect the new file. Any manual content edits will be overwritten.
	//
	// PATCH /v1/convai/knowledge-base/{documentation_id}/update-file
	UpdateFileDocumentRoute(ctx context.Context, req *BodyUpdateFileDocumentV1ConvaiKnowledgeBaseDocumentationIDUpdateFilePatchMultipart, params UpdateFileDocumentRouteParams) (UpdateFileDocumentRouteRes, error)
	// UpdatePhoneNumberRoute implements update_phone_number_route operation.
	//
	// Update assigned agent of a phone number.
	//
	// PATCH /v1/convai/phone-numbers/{phone_number_id}
	UpdatePhoneNumberRoute(ctx context.Context, req *UpdatePhoneNumberRequest, params UpdatePhoneNumberRouteParams) (UpdatePhoneNumberRouteRes, error)
	// UpdatePronunciationDictionaries implements update_pronunciation_dictionaries operation.
	//
	// Create a set of pronunciation dictionaries acting on a project. This will automatically mark text
	// within this project as requiring reconverting where the new dictionary would apply or the old one
	// no longer does.
	//
	// POST /v1/studio/projects/{project_id}/pronunciation-dictionaries
	UpdatePronunciationDictionaries(ctx context.Context, req *BodyCreatePronunciationDictionariesV1StudioProjectsProjectIDPronunciationDictionariesPost, params UpdatePronunciationDictionariesParams) (UpdatePronunciationDictionariesRes, error)
	// UpdateSecretRoute implements update_secret_route operation.
	//
	// Update an existing secret for the workspace.
	//
	// PATCH /v1/convai/secrets/{secret_id}
	UpdateSecretRoute(ctx context.Context, req *PatchWorkspaceSecretRequest, params UpdateSecretRouteParams) (UpdateSecretRouteRes, error)
	// UpdateSegmentLanguage implements update_segment_language operation.
	//
	// Modifies a single segment with new text and/or start/end times. Will update the values for only a
	// specific language of a segment. Does not automatically regenerate the dub.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PATCH /v1/dubbing/resource/{dubbing_id}/segment/{segment_id}/{language}
	UpdateSegmentLanguage(ctx context.Context, req *SegmentUpdatePayload, params UpdateSegmentLanguageParams) (UpdateSegmentLanguageRes, error)
	// UpdateSettingsRoute implements update_settings_route operation.
	//
	// Update Convai settings for the workspace.
	//
	// PATCH /v1/convai/settings
	UpdateSettingsRoute(ctx context.Context, req *PatchConvAISettingsRequest, params UpdateSettingsRouteParams) (UpdateSettingsRouteRes, error)
	// UpdateSpeaker implements update_speaker operation.
	//
	// Amend the metadata associated with a speaker, such as their voice. Both voice cloning and using
	// voices from the ElevenLabs library are supported.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PATCH /v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}
	UpdateSpeaker(ctx context.Context, req OptBodyUpdateMetadataForASpeakerV1DubbingResourceDubbingIDSpeakerSpeakerIDPatch, params UpdateSpeakerParams) (UpdateSpeakerRes, error)
	// UpdateWhatsappAccount implements update_whatsapp_account operation.
	//
	// Update a WhatsApp account.
	//
	// PATCH /v1/convai/whatsapp-accounts/{phone_number_id}
	UpdateWhatsappAccount(ctx context.Context, req *UpdateWhatsAppAccountRequest, params UpdateWhatsappAccountParams) (UpdateWhatsappAccountRes, error)
	// UpdateWorkspaceMember implements update_workspace_member operation.
	//
	// Updates attributes of a workspace member. Apart from the email identifier, all parameters will
	// remain unchanged unless specified. This endpoint may only be called by workspace administrators.
	//
	// POST /v1/workspace/members
	UpdateWorkspaceMember(ctx context.Context, req *BodyUpdateMemberV1WorkspaceMembersPost, params UpdateWorkspaceMemberParams) (UpdateWorkspaceMemberRes, error)
	// UploadFileRoute implements upload_file_route operation.
	//
	// Upload an image or PDF file for a conversation. Returns a unique file ID that can be used to
	// reference the file in the conversation.
	//
	// POST /v1/convai/conversations/{conversation_id}/files
	UploadFileRoute(ctx context.Context, req *BodyUploadFileV1ConvaiConversationsConversationIDFilesPostMultipart, params UploadFileRouteParams) (UploadFileRouteRes, error)
	// UsageCharacters implements usage_characters operation.
	//
	// (Deprecated) This endpoint is deprecated. Use
	// /v1/workspace/analytics/query/usage-by-product-over-time instead, which exposes the bucket size as
	// `interval_seconds` (an integer in seconds) rather than `aggregation_interval`. Returns the usage
	// metrics for the current user or the entire workspace they are part of. The response provides a
	// time axis based on the specified aggregation interval (default: day), with usage values for each
	// interval along that axis. Usage is broken down by the selected breakdown type. For example,
	// breakdown type "voice" will return the usage of each voice for each interval along the time axis.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/usage/character-stats
	UsageCharacters(ctx context.Context, params UsageCharactersParams) (UsageCharactersRes, error)
	// VerifyPvcVoiceCaptcha implements verify_pvc_voice_captcha operation.
	//
	// Submit captcha verification for PVC voice.
	//
	// POST /v1/voices/pvc/{voice_id}/captcha
	VerifyPvcVoiceCaptcha(ctx context.Context, req *BodyVerifyPVCVoiceCaptchaV1VoicesPvcVoiceIDCaptchaPostMultipart, params VerifyPvcVoiceCaptchaParams) (VerifyPvcVoiceCaptchaRes, error)
	// VideoToMusic implements video_to_music operation.
	//
	// Generate background music from one or more video files. Videos are combined in order. Optional
	// description and style tags influence the generated music.
	//
	// POST /v1/music/video-to-music
	VideoToMusic(ctx context.Context, req *BodyVideoToMusicV1MusicVideoToMusicPostMultipart, params VideoToMusicParams) (VideoToMusicRes, error)
	// WhatsappOutboundCall implements whatsapp_outbound_call operation.
	//
	// Make an outbound call via WhatsApp.
	//
	// POST /v1/convai/whatsapp/outbound-call
	WhatsappOutboundCall(ctx context.Context, req *BodyMakeAnOutboundCallViaWhatsAppV1ConvaiWhatsappOutboundCallPost, params WhatsappOutboundCallParams) (WhatsappOutboundCallRes, error)
	// WhatsappOutboundMessage implements whatsapp_outbound_message operation.
	//
	// Send an outbound message via WhatsApp.
	//
	// POST /v1/convai/whatsapp/outbound-message
	WhatsappOutboundMessage(ctx context.Context, req *BodySendAnOutboundMessageViaWhatsAppV1ConvaiWhatsappOutboundMessagePost, params WhatsappOutboundMessageParams) (WhatsappOutboundMessageRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
