// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AgentBranchResponse) setDefaults() {
	{
		val := float64(0)
		s.CurrentLivePercentage.SetTo(val)
	}
	{
		val := BranchProtectionStatus("writer_perms_required")
		s.ProtectionStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentBranchSummary) setDefaults() {
	{
		val := float64(0)
		s.CurrentLivePercentage.SetTo(val)
	}
	{
		val := bool(false)
		s.DraftExists.SetTo(val)
	}
	{
		val := BranchProtectionStatus("writer_perms_required")
		s.ProtectionStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentDeploymentPercentageStrategy) setDefaults() {
	{
		val := AgentDeploymentPercentageStrategyType("percentage")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentSummaryBatchSuccessfulResponseModel) setDefaults() {
	{
		val := AgentSummaryBatchSuccessfulResponseModelStatus("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *AgentSummaryResponseModel) setDefaults() {
	{
		val := bool(false)
		s.Archived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentTestFolderPathSegmentResponseModel) setDefaults() {
	{
		val := string("")
		s.Name.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ApiIntegrationOAuth2AuthCodeResponse) setDefaults() {
	{
		val := ApiIntegrationOAuth2AuthCodeResponseAuthType("api_integration_oauth2_auth_code")
		s.AuthType.SetTo(val)
	}
	{
		val := ApiIntegrationOAuth2AuthCodeResponseScopeSeparator(" ")
		s.ScopeSeparator.SetTo(val)
	}
	{
		val := OAuthConnectionStatus("active")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ApiIntegrationOAuth2CustomAppResponse) setDefaults() {
	{
		val := ApiIntegrationOAuth2CustomAppResponseAuthType("api_integration_oauth2_custom_app")
		s.AuthType.SetTo(val)
	}
	{
		val := ApiIntegrationOAuth2CustomAppResponseScopeSeparator(" ")
		s.ScopeSeparator.SetTo(val)
	}
	{
		val := OAuthConnectionStatus("active")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AsyncConversationMetadata) setDefaults() {
	{
		val := int(0)
		s.RetryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AudioNativeProjectSettingsResponseModel) setDefaults() {
	{
		val := AudioNativeProjectSettingsResponseModelStatus("ready")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AutoSyncInfo) setDefaults() {
	{
		val := bool(false)
		s.AutoRemove.SetTo(val)
	}
	{
		val := int(0)
		s.ConsecFailures.SetTo(val)
	}
	{
		val := int(7)
		s.MinimumFrequencyDays.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BasicAuthResponse) setDefaults() {
	{
		val := BasicAuthResponseAuthType("basic_auth")
		s.AuthType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BatchCallDetailedResponse) setDefaults() {
	{
		val := int(0)
		s.RetryCount = val
	}
	{
		val := int(0)
		s.TotalCallsDispatched = val
	}
	{
		val := int(0)
		s.TotalCallsFinished = val
	}
	{
		val := int(0)
		s.TotalCallsScheduled = val
	}
}

// setDefaults set default value of fields.
func (s *BatchCallResponse) setDefaults() {
	{
		val := int(0)
		s.RetryCount = val
	}
	{
		val := int(0)
		s.TotalCallsDispatched = val
	}
	{
		val := int(0)
		s.TotalCallsFinished = val
	}
	{
		val := int(0)
		s.TotalCallsScheduled = val
	}
}

// setDefaults set default value of fields.
func (s *BatchFailureResponseModel) setDefaults() {
	{
		val := BatchFailureResponseModelStatus("failure")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *BearerAuthResponse) setDefaults() {
	{
		val := BearerAuthResponseAuthType("bearer_auth")
		s.AuthType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAddSamplesToPVCVoiceV1VoicesPvcVoiceIDSamplesPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAddSharedVoiceV1VoicesAddPublicUserIDVoiceIDPost) setDefaults() {
	{
		val := bool(true)
		s.Bookmarked.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAddVoiceV1VoicesAddPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAudioIsolationStreamV1AudioIsolationStreamPostMultipart) setDefaults() {
	{
		val := BodyAudioIsolationStreamV1AudioIsolationStreamPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAudioIsolationV1AudioIsolationPostMultipart) setDefaults() {
	{
		val := BodyAudioIsolationV1AudioIsolationPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreateFolderV1ConvaiKnowledgeBaseFolderPost) setDefaults() {
	{
		val := bool(false)
		s.AutoRemove.SetTo(val)
	}
	{
		val := bool(false)
		s.EnableAutoSync.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreatePronunciationDictionariesV1StudioProjectsProjectIDPronunciationDictionariesPost) setDefaults() {
	{
		val := bool(true)
		s.InvalidateAffectedText.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreateStudioProjectV1StudioProjectsPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AcxVolumeNormalization.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoAssignVoices.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
	{
		val := bool(false)
		s.CreatePublishingRead.SetTo(val)
	}
	{
		val := bool(false)
		s.MatureContent.SetTo(val)
	}
	{
		val := QualityPresetType("standard")
		s.QualityPreset.SetTo(val)
	}
	{
		val := bool(false)
		s.VolumeNormalization.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreateURLDocumentV1ConvaiKnowledgeBaseURLPost) setDefaults() {
	{
		val := bool(false)
		s.AutoRemove.SetTo(val)
	}
	{
		val := bool(false)
		s.EnableAutoSync.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreatesAudioNativeEnabledProjectV1AudioNativePostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
	{
		val := int(0)
		s.Sessionization.SetTo(val)
	}
	{
		val := bool(false)
		s.Small.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyDubAVideoOrAnAudioFileV1DubbingPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.DisableVoiceCloning.SetTo(val)
	}
	{
		val := bool(false)
		s.DropBackgroundAudio.SetTo(val)
	}
	{
		val := bool(false)
		s.DubbingStudio.SetTo(val)
	}
	{
		val := bool(false)
		s.HighestResolution.SetTo(val)
	}
	{
		val := BodyDubAVideoOrAnAudioFileV1DubbingPostMultipartMode("automatic")
		s.Mode.SetTo(val)
	}
	{
		val := int(0)
		s.NumSpeakers.SetTo(val)
	}
	{
		val := string("auto")
		s.SourceLang.SetTo(val)
	}
	{
		val := bool(false)
		s.Watermark.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyEditVoiceV1VoicesVoiceIDEditPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.ModerateMetadata.SetTo(val)
	}
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyMergeABranchIntoATargetBranchV1ConvaiAgentsAgentIDBranchesSourceBranchIDMergePost) setDefaults() {
	{
		val := bool(true)
		s.ArchiveSourceBranch.SetTo(val)
	}
	{
		val := bool(false)
		s.Force.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPost) setDefaults() {
	{
		val := TelephonyDirection("inbound")
		s.Direction.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyRenderAudioOrVideoForTheGivenLanguageV1DubbingResourceDubbingIDRenderLanguagePost) setDefaults() {
	{
		val := bool(false)
		s.NormalizeVolume.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySoundGenerationV1SoundGenerationPost) setDefaults() {
	{
		val := bool(false)
		s.Loop.SetTo(val)
	}
	{
		val := string("eleven_text_to_sound_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := float64(0.3)
		s.PromptInfluence.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIDStreamPostMultipart) setDefaults() {
	{
		val := BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIDStreamPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
	{
		val := string("eleven_english_sts_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySpeechToSpeechV1SpeechToSpeechVoiceIDPostMultipart) setDefaults() {
	{
		val := BodySpeechToSpeechV1SpeechToSpeechVoiceIDPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
	{
		val := string("eleven_english_sts_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySpeechToTextV1SpeechToTextPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.DetectSpeakerRoles.SetTo(val)
	}
	{
		val := bool(false)
		s.Diarize.SetTo(val)
	}
	{
		val := string("enumerated_entity_type")
		s.EntityRedactionMode.SetTo(val)
	}
	{
		val := BodySpeechToTextV1SpeechToTextPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
	{
		val := bool(false)
		s.NoVerbatim.SetTo(val)
	}
	{
		val := bool(true)
		s.TagAudioEvents.SetTo(val)
	}
	{
		val := BodySpeechToTextV1SpeechToTextPostMultipartTimestampsGranularity("word")
		s.TimestampsGranularity.SetTo(val)
	}
	{
		val := bool(false)
		s.UseMultiChannel.SetTo(val)
	}
	{
		val := bool(false)
		s.UseSpeakerLibrary.SetTo(val)
	}
	{
		val := bool(false)
		s.Webhook.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStemSeparationV1MusicStemSeparationPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.SignWithC2pa.SetTo(val)
	}
	{
		val := BodyStemSeparationV1MusicStemSeparationPostMultipartStemVariationID("six_stems_v1")
		s.StemVariationID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStreamChapterAudioV1StudioProjectsProjectIDChaptersChapterIDSnapshotsChapterSnapshotIDStreamPost) setDefaults() {
	{
		val := bool(false)
		s.ConvertToMpeg.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStreamStudioProjectAudioV1StudioProjectsProjectIDSnapshotsProjectSnapshotIDStreamPost) setDefaults() {
	{
		val := bool(false)
		s.ConvertToMpeg.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueFullWithTimestamps) setDefaults() {
	{
		val := BodyTextToDialogueFullWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPost) setDefaults() {
	{
		val := BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPostApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueMultiVoiceV1TextToDialoguePost) setDefaults() {
	{
		val := BodyTextToDialogueMultiVoiceV1TextToDialoguePostApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueStreamWithTimestamps) setDefaults() {
	{
		val := BodyTextToDialogueStreamWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechFull) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechFullApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechFullWithTimestamps) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechFullWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechStream) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechStreamApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechStreamWithTimestamps) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechStreamWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateAgentBranchV1ConvaiAgentsAgentIDBranchesBranchIDPatch) setDefaults() {
	{
		val := BranchProtectionStatus("writer_perms_required")
		s.ProtectionStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateAudioNativeProjectContentV1AudioNativeProjectIDContentPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoPublish.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdatePVCVoiceSampleV1VoicesPvcVoiceIDSamplesSampleIDPost) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateStudioProjectContentV1StudioProjectsProjectIDContentPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) setDefaults() {
	{
		val := bool(false)
		s.VolumeNormalization.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyVideoToMusicV1MusicVideoToMusicPostMultipart) setDefaults() {
	{
		val := BodyVideoToMusicV1MusicVideoToMusicPostMultipartModelID("music_v1")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.SignWithC2pa.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CaptionStyleTemplateModel) setDefaults() {
	{
		val := bool(false)
		s.RequiresHighFps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConstantSchemaOverride) setDefaults() {
	{
		val := ConstantSchemaOverrideSource("constant")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContextualUpdateInfo) setDefaults() {
	{
		val := bool(false)
		s.IsSuperseded.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConvAIStoredSecretDependencies) setDefaults() {
	{
		val := bool(false)
		s.AgentsHasMore.SetTo(val)
	}
	{
		val := bool(false)
		s.PhoneNumbersHasMore.SetTo(val)
	}
	{
		val := bool(false)
		s.ToolsHasMore.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConvAIWebhooks) setDefaults() {
	{
		val := WebhookTranscriptFormat("json")
		s.TranscriptFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationASRUsageModel) setDefaults() {
	{
		val := float64(0)
		s.TotalAudioInputSeconds.SetTo(val)
	}
	{
		val := int(0)
		s.TotalTranscriptionCalls.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationChargingCommonModel) setDefaults() {
	{
		val := bool(false)
		s.DevDiscount.SetTo(val)
	}
	{
		val := float64(0)
		s.FreeLlmDollarsConsumed.SetTo(val)
	}
	{
		val := float64(0)
		s.FreeMinutesConsumed.SetTo(val)
	}
	{
		val := bool(false)
		s.IsBurst.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationDeletionSettings) setDefaults() {
	{
		val := bool(false)
		s.DeleteAudio.SetTo(val)
	}
	{
		val := bool(false)
		s.DeleteTranscriptAndPii.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryElevenAssistantCommonModel) setDefaults() {
	{
		val := bool(false)
		s.IsElevenAssistant.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryExotelPhoneCallModel) setDefaults() {
	{
		val := TelephonyDirection("inbound")
		s.Direction = val
	}
	{
		val := ConversationHistoryExotelPhoneCallModelType("exotel")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryFeedbackCommonModel) setDefaults() {
	{
		val := int(0)
		s.Dislikes.SetTo(val)
	}
	{
		val := int(0)
		s.Likes.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryMetadataCommonModel) setDefaults() {
	{
		val := AgentDefinitionSource("unknown")
		s.AgentCreatedFrom.SetTo(val)
	}
	{
		val := AgentDefinitionSource("unknown")
		s.AgentLastUpdatedFrom.SetTo(val)
	}
	{
		val := AuthorizationMethod("public")
		s.AuthorizationMethod.SetTo(val)
	}
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := string("")
		s.TerminationReason.SetTo(val)
	}
	{
		val := bool(false)
		s.TextOnly.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistorySIPTrunkingPhoneCallModel) setDefaults() {
	{
		val := TelephonyDirection("inbound")
		s.Direction = val
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModelOutput) setDefaults() {
	{
		val := string("")
		s.CredentialID = val
	}
	{
		val := string("")
		s.ErrorType = val
	}
	{
		val := string("")
		s.IntegrationConnectionID = val
	}
	{
		val := string("")
		s.IntegrationID = val
	}
	{
		val := bool(false)
		s.IsBlocked = val
	}
	{
		val := string("")
		s.RawErrorMessage = val
	}
	{
		val := float64(0)
		s.ToolLatencySecs = val
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptCommonModelOutput) setDefaults() {
	{
		val := bool(false)
		s.Interrupted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptOtherToolsResultCommonModel) setDefaults() {
	{
		val := string("")
		s.ErrorType.SetTo(val)
	}
	{
		val := bool(false)
		s.IsBlocked.SetTo(val)
	}
	{
		val := string("")
		s.RawErrorMessage.SetTo(val)
	}
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptResponseModel) setDefaults() {
	{
		val := bool(false)
		s.Interrupted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptSystemToolResultCommonModelOutput) setDefaults() {
	{
		val := string("")
		s.ErrorType.SetTo(val)
	}
	{
		val := bool(false)
		s.IsBlocked.SetTo(val)
	}
	{
		val := string("")
		s.RawErrorMessage.SetTo(val)
	}
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallApiIntegrationWebhookDetailsOutput) setDefaults() {
	{
		val := string("")
		s.CredentialID = val
	}
	{
		val := string("")
		s.IntegrationConnectionID = val
	}
	{
		val := string("")
		s.IntegrationID = val
	}
	{
		val := ConversationHistoryTranscriptToolCallApiIntegrationWebhookDetailsOutputType("api_integration_webhook")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallClientDetails) setDefaults() {
	{
		val := ConversationHistoryTranscriptToolCallClientDetailsType("client")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallMCPDetails) setDefaults() {
	{
		val := string("")
		s.McpToolDescription.SetTo(val)
	}
	{
		val := string("")
		s.McpToolName.SetTo(val)
	}
	{
		val := bool(false)
		s.RequiresApproval.SetTo(val)
	}
	{
		val := ConversationHistoryTranscriptToolCallMCPDetailsType("mcp")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallWebhookDetails) setDefaults() {
	{
		val := ConversationHistoryTranscriptToolCallWebhookDetailsType("webhook")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptWorkflowToolsResultCommonModelOutput) setDefaults() {
	{
		val := string("")
		s.ErrorType.SetTo(val)
	}
	{
		val := bool(false)
		s.IsBlocked.SetTo(val)
	}
	{
		val := string("")
		s.RawErrorMessage.SetTo(val)
	}
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTwilioPhoneCallModel) setDefaults() {
	{
		val := TelephonyDirection("inbound")
		s.Direction = val
	}
}

// setDefaults set default value of fields.
func (s *ConversationInitiationSourceInfo) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationSummaryResponseModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := TelephonyDirection("inbound")
		s.Direction.SetTo(val)
	}
	{
		val := string("")
		s.TerminationReason.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationTTSUsageModel) setDefaults() {
	{
		val := float64(0)
		s.TotalAudioOutputSeconds.SetTo(val)
	}
	{
		val := int(0)
		s.TotalCharacters.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationVoiceUsageModel) setDefaults() {
	{
		val := float64(0)
		s.AudioOutputSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateOrderRequest) setDefaults() {
	{
		val := bool(false)
		s.Sandbox.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateOrderResponse) setDefaults() {
	{
		val := bool(false)
		s.Sandbox.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CueOptionsRequest) setDefaults() {
	{
		val := int(42)
		s.MaxCharsPerLine.SetTo(val)
	}
	{
		val := int(7000)
		s.MaxDurationMs.SetTo(val)
	}
	{
		val := int(2)
		s.MaxLinesPerCue.SetTo(val)
	}
	{
		val := int(1000)
		s.MinDurationMs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CustomHeaderAuthResponse) setDefaults() {
	{
		val := CustomHeaderAuthResponseAuthType("custom_header_auth")
		s.AuthType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DashboardCallSuccessChartModel) setDefaults() {
	{
		val := DashboardCallSuccessChartModelType("call_success")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DashboardCriteriaChartModel) setDefaults() {
	{
		val := DashboardCriteriaChartModelType("criteria")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DashboardDataCollectionChartModel) setDefaults() {
	{
		val := DashboardDataCollectionChartModelType("data_collection")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DeliverableInfo) setDefaults() {
	{
		val := int(1)
		s.Version.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentAvailableAgentIdentifier) setDefaults() {
	{
		val := DependentAvailableAgentIdentifierType("available")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentAvailableMCPServerIdentifier) setDefaults() {
	{
		val := DependentAvailableMCPServerIdentifierType("available")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentAvailableToolIdentifier) setDefaults() {
	{
		val := DependentAvailableToolIdentifierType("available")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentUnknownAgentIdentifier) setDefaults() {
	{
		val := DependentUnknownAgentIdentifierType("unknown")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentUnknownMCPServerIdentifier) setDefaults() {
	{
		val := DependentUnknownMCPServerIdentifierType("unknown")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentUnknownToolIdentifier) setDefaults() {
	{
		val := DependentUnknownToolIdentifierType("unknown")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DocxExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubOrderItemRequest) setDefaults() {
	{
		val := DubOrderItemRequestKind("dub")
		s.Kind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingMetadataResponse) setDefaults() {
	{
		val := bool(false)
		s.Editable.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingTranscriptCharacter) setDefaults() {
	{
		val := float64(0)
		s.EndS.SetTo(val)
	}
	{
		val := float64(0)
		s.StartS.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingTranscriptUtterance) setDefaults() {
	{
		val := float64(0)
		s.EndS.SetTo(val)
	}
	{
		val := string("unknown")
		s.SpeakerID.SetTo(val)
	}
	{
		val := float64(0)
		s.StartS.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingTranscriptWord) setDefaults() {
	{
		val := float64(0)
		s.EndS.SetTo(val)
	}
	{
		val := float64(0)
		s.StartS.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
	{
		val := string("unknown")
		s.WordType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DynamicVariableAssignment) setDefaults() {
	{
		val := bool(false)
		s.PreserveNativeType.SetTo(val)
	}
	{
		val := bool(false)
		s.Sanitize.SetTo(val)
	}
	{
		val := DynamicVariableAssignmentSource("response")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DynamicVariableSchemaOverride) setDefaults() {
	{
		val := DynamicVariableSchemaOverrideSource("dynamic_variable")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EndCallToolResultModel) setDefaults() {
	{
		val := EndCallToolResultModelResultType("end_call_success")
		s.ResultType.SetTo(val)
	}
	{
		val := EndCallToolResultModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FeatureStatusCommonModel) setDefaults() {
	{
		val := bool(false)
		s.Enabled.SetTo(val)
	}
	{
		val := bool(false)
		s.Used.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FeaturesUsageCommonModel) setDefaults() {
	{
		val := bool(false)
		s.IsLivekit.SetTo(val)
	}
	{
		val := bool(false)
		s.PiiZrmAgent.SetTo(val)
	}
	{
		val := bool(false)
		s.PiiZrmWorkspace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FeedbackResponseModel) setDefaults() {
	{
		val := string("not_reviewed")
		s.ReviewStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetAgentTestFolderResponseModel) setDefaults() {
	{
		val := int(0)
		s.ChildrenCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetConvAISettingsResponseModel) setDefaults() {
	{
		val := bool(false)
		s.CanUseMcpServers.SetTo(val)
	}
	{
		val := LivekitStackType("standard")
		s.DefaultLivekitStack.SetTo(val)
	}
	{
		val := int(10)
		s.RagRetentionPeriodDays.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetConversationResponseModel) setDefaults() {
	{
		val := string("agent")
		s.ConversationProduct.SetTo(val)
	}
	{
		val := string("production")
		s.Environment.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetKnowledgeBaseFileResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsFrozen.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetKnowledgeBaseFolderResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsFrozen.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetKnowledgeBaseSummaryFileResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsFrozen.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetKnowledgeBaseSummaryFolderResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsFrozen.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetLibraryVoicesResponseModel) setDefaults() {
	{
		val := int(0)
		s.TotalCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetOrCreateRAGIndexRequestModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberExotelResponseModel) setDefaults() {
	{
		val := GetPhoneNumberExotelResponseModelProvider("exotel")
		s.Provider.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsInbound.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsOutbound.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberInboundSIPTrunkConfigResponseModel) setDefaults() {
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption = val
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberOutboundSIPTrunkConfigResponseModel) setDefaults() {
	{
		val := bool(false)
		s.HasOutboundTrunk.SetTo(val)
	}
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption = val
	}
	{
		val := SIPTrunkTransportEnum("auto")
		s.Transport = val
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberSIPTrunkResponseModel) setDefaults() {
	{
		val := LivekitStackType("standard")
		s.LivekitStack = val
	}
	{
		val := GetPhoneNumberSIPTrunkResponseModelProvider("sip_trunk")
		s.Provider.SetTo(val)
	}
	{
		val := bool(true)
		s.StoreSipMessages.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsInbound.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsOutbound.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberTwilioResponseModel) setDefaults() {
	{
		val := GetPhoneNumberTwilioResponseModelProvider("twilio")
		s.Provider.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsInbound.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsOutbound.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetResponseUnitTestResponseModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := string("")
		s.SuccessCondition.SetTo(val)
	}
	{
		val := GetResponseUnitTestResponseModelType("llm")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetSIPLogMessagesResponse) setDefaults() {
	{
		val := bool(false)
		s.HasMore.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetSimulationTestResponseModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := LLM("gemini-2.5-flash")
		s.EvaluationModel.SetTo(val)
	}
	{
		val := LLM("gemini-2.5-flash")
		s.SimulatedUserModel.SetTo(val)
	}
	{
		val := int(5)
		s.SimulationMaxTurns.SetTo(val)
	}
	{
		val := string("")
		s.SimulationScenario.SetTo(val)
	}
	{
		val := string("")
		s.SuccessCondition.SetTo(val)
	}
	{
		val := GetSimulationTestResponseModelType("simulation")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetTestSuiteInvocationResponseModel) setDefaults() {
	{
		val := int(1)
		s.RepeatCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetToolCallUnitTestResponseModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := GetToolCallUnitTestResponseModelType("tool")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetWhatsAppAccountResponse) setDefaults() {
	{
		val := bool(true)
		s.EnableAudioMessageResponse.SetTo(val)
	}
	{
		val := bool(true)
		s.EnableMessaging.SetTo(val)
	}
	{
		val := bool(false)
		s.IsTokenExpired.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *HtmlExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InboundSIPTrunkConfigRequestModel) setDefaults() {
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *KnowledgeBaseLocator) setDefaults() {
	{
		val := DocumentUsageModeEnum("auto")
		s.UsageMode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *KnowledgeBaseRagToolResultModel) setDefaults() {
	{
		val := int(0)
		s.ChunkCount.SetTo(val)
	}
	{
		val := string("Referenced knowledge base.")
		s.Message.SetTo(val)
	}
	{
		val := KnowledgeBaseRagToolResultModelResultType("knowledge_base_rag_success")
		s.ResultType.SetTo(val)
	}
	{
		val := KnowledgeBaseRagToolStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *KnowledgeBaseSummaryBatchSuccessfulResponseModel) setDefaults() {
	{
		val := KnowledgeBaseSummaryBatchSuccessfulResponseModelStatus("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *LLMDeprecationInfoModel) setDefaults() {
	{
		val := int(0)
		s.FallbackPercentage.SetTo(val)
	}
	{
		val := bool(false)
		s.IsInFallbackPeriod.SetTo(val)
	}
	{
		val := bool(false)
		s.IsInWarningPeriod.SetTo(val)
	}
	{
		val := LLM("gemini-2.5-flash")
		s.Llm = val
	}
	{
		val := LLM("gemini-2.5-flash")
		s.ReplacementModel.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LLMInfoModelInput) setDefaults() {
	{
		val := LLM("gemini-2.5-flash")
		s.Llm = val
	}
}

// setDefaults set default value of fields.
func (s *LLMSchemaOverride) setDefaults() {
	{
		val := LLMSchemaOverrideSource("llm")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LLMTokensCategoryUsage) setDefaults() {
	{
		val := float64(0)
		s.Price.SetTo(val)
	}
	{
		val := int(0)
		s.Tokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LLMUsageCalculatorLLMResponseModel) setDefaults() {
	{
		val := LLM("gemini-2.5-flash")
		s.Llm = val
	}
}

// setDefaults set default value of fields.
func (s *LanguageDetectionToolResultModel) setDefaults() {
	{
		val := LanguageDetectionToolResultModelResultType("language_detection_success")
		s.ResultType.SetTo(val)
	}
	{
		val := LanguageDetectionToolResultModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LiteralJsonSchemaProperty) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
	{
		val := string("")
		s.DynamicVariable.SetTo(val)
	}
	{
		val := bool(false)
		s.IsOmitted.SetTo(val)
	}
	{
		val := bool(false)
		s.IsSystemProvided.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPToolConfigOverrideOutput) setDefaults() {
	{
		val := ToolExecutionMode("immediate")
		s.ExecutionMode.SetTo(val)
	}
	{
		val := PreToolSpeechMode("auto")
		s.PreToolSpeech.SetTo(val)
	}
	{
		val := ToolCallSoundBehavior("auto")
		s.ToolCallSoundBehavior.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MTLSAuthResponse) setDefaults() {
	{
		val := MTLSAuthResponseAuthType("mtls")
		s.AuthType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelRatesResponseModel) setDefaults() {
	{
		val := float64(1)
		s.CostDiscountMultiplier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelSettingsResponseModel) setDefaults() {
	{
		val := float64(0.5)
		s.Stability.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OAuth2ClientCredsResponse) setDefaults() {
	{
		val := OAuth2ClientCredsResponseAuthType("oauth2_client_credentials")
		s.AuthType.SetTo(val)
	}
	{
		val := bool(false)
		s.BasicAuthInHeader.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OAuth2JWTResponse) setDefaults() {
	{
		val := OAuth2JWTResponseAlgorithm("HS256")
		s.Algorithm.SetTo(val)
	}
	{
		val := OAuth2JWTResponseAuthType("oauth2_jwt")
		s.AuthType.SetTo(val)
	}
	{
		val := int(3600)
		s.ExpirationSeconds.SetTo(val)
	}
	{
		val := OAuth2JWTResponseTokenResponseField("access_token")
		s.TokenResponseField.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OmitSchemaOverride) setDefaults() {
	{
		val := OmitSchemaOverrideSource("omit")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OrchestratorToolMockBehaviorConfig) setDefaults() {
	{
		val := MockNoMatchBehavior("raise_error")
		s.FallbackStrategy.SetTo(val)
	}
	{
		val := MockingStrategy("none")
		s.MockingStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OrderResponse) setDefaults() {
	{
		val := bool(false)
		s.Sandbox.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OrderSummary) setDefaults() {
	{
		val := bool(false)
		s.Sandbox.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OutboundSIPTrunkConfigRequestModel) setDefaults() {
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption.SetTo(val)
	}
	{
		val := SIPTrunkTransportEnum("auto")
		s.Transport.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PairedLanguagesResponse) setDefaults() {
	{
		val := PairedLanguagesResponseKind("pair")
		s.Kind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PatchConvAISettingsRequest) setDefaults() {
	{
		val := bool(false)
		s.CanUseMcpServers.SetTo(val)
	}
	{
		val := LivekitStackType("standard")
		s.DefaultLivekitStack.SetTo(val)
	}
	{
		val := int(10)
		s.RagRetentionPeriodDays.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PdfExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PlayDTMFResultErrorModel) setDefaults() {
	{
		val := PlayDTMFResultErrorModelResultType("play_dtmf_error")
		s.ResultType.SetTo(val)
	}
	{
		val := PlayDTMFResultErrorModelStatus("error")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PlayDTMFResultSuccessModel) setDefaults() {
	{
		val := PlayDTMFResultSuccessModelResultType("play_dtmf_success")
		s.ResultType.SetTo(val)
	}
	{
		val := PlayDTMFResultSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PrivateKeyJWTResponse) setDefaults() {
	{
		val := PrivateKeyJWTResponseAlgorithm("HS256")
		s.Algorithm.SetTo(val)
	}
	{
		val := PrivateKeyJWTResponseAuthType("private_key_jwt")
		s.AuthType.SetTo(val)
	}
	{
		val := int(3600)
		s.ExpirationSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ProjectResponseModel) setDefaults() {
	{
		val := bool(true)
		s.CaptionsEnabled.SetTo(val)
	}
	{
		val := bool(true)
		s.ChaptersEnabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptAgentAPIModelOverrideInput) setDefaults() {
	{
		val := LLM("gemini-2.5-flash")
		s.Llm.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptAgentAPIModelOverrideOutput) setDefaults() {
	{
		val := LLM("gemini-2.5-flash")
		s.Llm.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RAGDocumentIndexResponseModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *RAGIndexBatchSuccessfulResponseModel) setDefaults() {
	{
		val := RAGIndexBatchSuccessfulResponseModelStatus("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *RAGIndexOverviewEmbeddingModelResponseModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *RAGIndexRequestModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *RagRetrievalInfo) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.EmbeddingModel = val
	}
}

// setDefaults set default value of fields.
func (s *ResponseUnitTestModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := string("")
		s.SuccessCondition.SetTo(val)
	}
	{
		val := ResponseUnitTestModelType("llm")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RunConversationEvaluationsRequest) setDefaults() {
	{
		val := AnalysisScope("conversation")
		s.Scope.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ScopedAnalysisResult) setDefaults() {
	{
		val := AnalysisScope("conversation")
		s.Scope = val
	}
}

// setDefaults set default value of fields.
func (s *SegmentedJsonExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SimulationTestModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := LLM("gemini-2.5-flash")
		s.EvaluationModel.SetTo(val)
	}
	{
		val := LLM("gemini-2.5-flash")
		s.SimulatedUserModel.SetTo(val)
	}
	{
		val := int(5)
		s.SimulationMaxTurns.SetTo(val)
	}
	{
		val := string("")
		s.SimulationScenario.SetTo(val)
	}
	{
		val := string("")
		s.SuccessCondition.SetTo(val)
	}
	{
		val := SimulationTestModelType("simulation")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SimulationToolMockBehaviorConfig) setDefaults() {
	{
		val := MockNoMatchBehavior("raise_error")
		s.FallbackStrategy.SetTo(val)
	}
	{
		val := MockingStrategy("none")
		s.MockingStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SingleLanguagesResponse) setDefaults() {
	{
		val := SingleLanguagesResponseKind("single")
		s.Kind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SkipTurnToolResponseModel) setDefaults() {
	{
		val := SkipTurnToolResponseModelResultType("skip_turn_success")
		s.ResultType.SetTo(val)
	}
	{
		val := SkipTurnToolResponseModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SlackBotAuthResponse) setDefaults() {
	{
		val := SlackBotAuthResponseAuthType("slack_bot_auth")
		s.AuthType.SetTo(val)
	}
	{
		val := SlackBotAuthResponseProvider("Slack")
		s.Provider.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SrtExportOptions) setDefaults() {
	{
		val := bool(false)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
	{
		val := int(42)
		s.MaxCharactersPerLine.SetTo(val)
	}
	{
		val := int(84)
		s.MaxSegmentChars.SetTo(val)
	}
	{
		val := float64(4)
		s.MaxSegmentDurationS.SetTo(val)
	}
	{
		val := float64(0.8)
		s.SegmentOnSilenceLongerThanS.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *StudioAgentToolSettingsModel) setDefaults() {
	{
		val := bool(false)
		s.SkipConfirmation.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubtitleOrderItemRequest) setDefaults() {
	{
		val := SubtitleOrderItemRequestKind("subtitles")
		s.Kind.SetTo(val)
	}
	{
		val := bool(false)
		s.Sdh.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TelephonyCallConfig) setDefaults() {
	{
		val := int(60)
		s.RingingTimeoutSecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestConditionRationaleCommonModel) setDefaults() {
	{
		val := string("")
		s.Summary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestInvocationSummaryResponseModel) setDefaults() {
	{
		val := int(1)
		s.RepeatCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestRunMetadata) setDefaults() {
	{
		val := TestRunMetadataTestType("llm")
		s.TestType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestToolResultModel) setDefaults() {
	{
		val := string("Skipping tool call in test mode")
		s.Reason.SetTo(val)
	}
	{
		val := TestToolResultModelResultType("testing_tool_result")
		s.ResultType.SetTo(val)
	}
	{
		val := TestToolResultModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestsFeatureUsageCommonModel) setDefaults() {
	{
		val := bool(false)
		s.Enabled.SetTo(val)
	}
	{
		val := bool(false)
		s.TestsRanAfterLastModification.SetTo(val)
	}
	{
		val := bool(false)
		s.TestsRanInLast7Days.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ToolCallUnitTestModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := ToolCallUnitTestModelType("tool")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ToolExecutionResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsError.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToAgentToolResultErrorModel) setDefaults() {
	{
		val := TransferToAgentToolResultErrorModelResultType("transfer_to_agent_error")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToAgentToolResultErrorModelStatus("error")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToAgentToolResultSuccessModel) setDefaults() {
	{
		val := int(0)
		s.DelayMs.SetTo(val)
	}
	{
		val := bool(false)
		s.EnableTransferredAgentFirstMessage.SetTo(val)
	}
	{
		val := bool(false)
		s.PreserveClientTtsOverrides.SetTo(val)
	}
	{
		val := TransferToAgentToolResultSuccessModelResultType("transfer_to_agent_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToAgentToolResultSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultErrorModel) setDefaults() {
	{
		val := TransferToNumberResultErrorModelResultType("transfer_to_number_error")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultErrorModelStatus("error")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultExotelSuccessModel) setDefaults() {
	{
		val := TransferToNumberResultExotelSuccessModelResultType("transfer_to_number_exotel_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultExotelSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultSipSuccessModel) setDefaults() {
	{
		val := TransferToNumberResultSipSuccessModelResultType("transfer_to_number_sip_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultSipSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultTwilioSuccessModel) setDefaults() {
	{
		val := TransferToNumberResultTwilioSuccessModelResultType("transfer_to_number_twilio_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultTwilioSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TxtExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
	{
		val := int(100)
		s.MaxCharactersPerLine.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestRunResponseModel) setDefaults() {
	{
		val := string("Unknown Test")
		s.TestName.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestSummaryResponseModel) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := AgentTestEntityType("test")
		s.EntityType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestToolCallEvaluationModelOutput) setDefaults() {
	{
		val := bool(false)
		s.VerifyAbsence.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestWorkflowNodeTransitionEvaluationNodeId) setDefaults() {
	{
		val := UnitTestWorkflowNodeTransitionEvaluationNodeIdType("node_id")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdatePhoneNumberRequest) setDefaults() {
	{
		val := LivekitStackType("standard")
		s.LivekitStack.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UrlSecretAuthResponse) setDefaults() {
	{
		val := UrlSecretAuthResponseAuthType("url_secret")
		s.AuthType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsAPIKeyHashed.SetTo(val)
	}
	{
		val := bool(false)
		s.ShowComplianceTerms.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceDesignRequestModel) setDefaults() {
	{
		val := bool(false)
		s.AutoGenerateText.SetTo(val)
	}
	{
		val := float64(5)
		s.GuidanceScale.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Loudness.SetTo(val)
	}
	{
		val := VoiceDesignRequestModelModelID("eleven_multilingual_ttv_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.ShouldEnhance.SetTo(val)
	}
	{
		val := bool(false)
		s.StreamPreviews.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceMailDetectionResultSuccessModel) setDefaults() {
	{
		val := VoiceMailDetectionResultSuccessModelResultType("voicemail_detection_success")
		s.ResultType.SetTo(val)
	}
	{
		val := VoiceMailDetectionResultSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoicePreviewsRequestModel) setDefaults() {
	{
		val := bool(false)
		s.AutoGenerateText.SetTo(val)
	}
	{
		val := float64(5)
		s.GuidanceScale.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Loudness.SetTo(val)
	}
	{
		val := float64(0.9)
		s.Quality.SetTo(val)
	}
	{
		val := bool(false)
		s.ShouldEnhance.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceRemixRequestModel) setDefaults() {
	{
		val := bool(false)
		s.AutoGenerateText.SetTo(val)
	}
	{
		val := float64(2)
		s.GuidanceScale.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Loudness.SetTo(val)
	}
	{
		val := bool(false)
		s.StreamPreviews.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsLegacy.SetTo(val)
	}
	{
		val := bool(false)
		s.IsMixed.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceSettingsResponseModel) setDefaults() {
	{
		val := float64(0.75)
		s.SimilarityBoost.SetTo(val)
	}
	{
		val := float64(1)
		s.Speed.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Stability.SetTo(val)
	}
	{
		val := float64(0)
		s.Style.SetTo(val)
	}
	{
		val := bool(true)
		s.UseSpeakerBoost.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppAuthResponse) setDefaults() {
	{
		val := WhatsAppAuthResponseAuthType("whatsapp_auth")
		s.AuthType.SetTo(val)
	}
	{
		val := WhatsAppAuthResponseProvider("whatsapp")
		s.Provider.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppConversationInfo) setDefaults() {
	{
		val := WhatsAppConversationInfoDirection("unknown")
		s.Direction.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateBodyComponentParams) setDefaults() {
	{
		val := WhatsAppTemplateBodyComponentParamsType("body")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateButtonComponentParams) setDefaults() {
	{
		val := WhatsAppTemplateButtonComponentParamsType("button")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateDocumentParam) setDefaults() {
	{
		val := WhatsAppTemplateDocumentParamType("document")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateHeaderComponentParams) setDefaults() {
	{
		val := WhatsAppTemplateHeaderComponentParamsType("header")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateImageParam) setDefaults() {
	{
		val := WhatsAppTemplateImageParamType("image")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateLocationParam) setDefaults() {
	{
		val := WhatsAppTemplateLocationParamType("location")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppTemplateTextParam) setDefaults() {
	{
		val := WhatsAppTemplateTextParamType("text")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowFeaturesUsageCommonModel) setDefaults() {
	{
		val := bool(false)
		s.Enabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolEdgeStepModel) setDefaults() {
	{
		val := WorkflowToolEdgeStepModelType("edge")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolMaxIterationsExceededStepModel) setDefaults() {
	{
		val := WorkflowToolMaxIterationsExceededStepModelType("max_iterations_exceeded")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolNestedToolsStepModelOutput) setDefaults() {
	{
		val := WorkflowToolNestedToolsStepModelOutputType("nested_tools")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkspaceApiKeyResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkspaceBatchCallsResponse) setDefaults() {
	{
		val := bool(false)
		s.HasMore.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkspaceGroupResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsScimSynced.SetTo(val)
	}
}
